### ISSUE TITLE
LANG unset

### ISSUE THREAD

**Issue by yatish27** [rubinius/rubinius#2604]
*rbx-version* rbx-head
*uname -a*  Darwin Yatishs-MacBook-Pro.local 12.4.0 Darwin Kernel Version 12.4.0: Wed May  1 17:57:12 PDT 2013; root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64
After installing rbx head via rvm, LANG needs to be unset and added explicitly 
export LANG=en_US.utf-8 to get gems installed else the following error is raised
    
    ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in US-ASCII

**Comment by brixen** [comment]
Closing this because the data being processed really does have multi-byte sequences and the correct encoding setting is UTF-8.

In Rubinius, nearly every IO method is implemented in Ruby and uses the encoding of the String. In MRI, most (or all) of the operations are in C and may be concatenating or splitting bytes without checking the encoding. Ultimately, the fix would likely be *ignoring* the correct encoding checks, and that sort of special-casing does not contribute to overall quality.

If anyone really wants to present a proposed patch, feel free to re-open or open a new issue.
