### ISSUE TITLE
RSpec / Rails: Slow startup/run times.

### ISSUE THREAD

**Issue by mrrooijen** [rubinius/rubinius#2730]
I **really** want to use Rubinius. However, I'm having a hard time dealing with the extremely slow process boot times. Particularly when running tests.

For example, under Ruby 2.1.0-preview1 it takes about 2 seconds for my rspec/rails process to boot, and another 0.75s to run the 64 tests I have.

Now, switching to RBX it takes about 30 seconds for the RSpec process to boot, and then another 7 seconds to run the tests.

Is this normal?

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
