### ISSUE TITLE
BigDecimal is too slow (need benchmark)

### ISSUE THREAD

**Issue by brodock** [rubinius/rubinius#2746]
I was trying BigDecimal in many different ruby implementations, and noted that bigdecimal in rubinius is many times slower than MRI and jRuby.

The benchmark I'm using is the one at this question on stackoverflow:

http://stackoverflow.com/questions/8514167/float-vs-decimal-in-activerecord

I would like to ask if porting this benchmark, following the instructions here: http://rubini.us/doc/en/how-to/write-benchmarks/ will be useful for the project?

Here are my specs:

rubinius 2.1.1.n301 (2.1.0 4892d3f5 2013-10-28 JI) [x86_64-darwin13.0.0]

and these are the results for "BigDecimal":

```
 30.243971   0.207703  30.451674 ( 30.686957)
```

float:

```
  2.819188   0.017359   2.836547 (  2.857857)
```

the MRI version:
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]

BigDecimal:

```
  6.820000   0.070000   6.890000 (  6.915909)
```

float:

```
  0.780000   0.000000   0.780000 (  0.785991) 
```

and finally jRuby:
jruby 1.7.5 (1.9.3p392) 2013-10-07 74e9291 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_40-b43 [darwin-x86_64]

BigDecimal:

```
  1.810000   0.040000   1.850000 (  1.827000)
```

float:

```
  0.800000   0.030000   0.830000 (  0.823000)
```

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
