### ISSUE TITLE
String#[]= is slow

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#2830]
String#[]= is 3 times slower in rubinius than in mri 2.1.0.preview1            

It is approx 40 percent of the problem with the bm_word_anagrams.rb benchmark
  which is 3 times slower in rubinius than mri

test code:

7_000_000.times do
  s = "abcdefghijk"
  s[5] = "x"
end

Timings:

rubinius 2.2.1
real    0m9.811s
user    0m10.204s
sys 0m0.103s

ruby 2.1.0.preview1
real    0m2.910s
user    0m2.878s
sys 0m0.012s

rubinius style benchmark: https://gist.github.com/kwleland/7988659

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
