### ISSUE TITLE
Bignum#& is slow

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#2833]
Bignum#& is 6 times slower in rubinius than in mri.

This counts for approximately 75 percent of the relative slowness in
  bm_meteor_contest.rb which itself is 2.8 times slower in rubinius
  than in mri.

test code:

  a = 123456790123456789012345678901234567890

  16_000_000.times do
     b = a & 27
  end

timings:

Rubinius 2.2.1:
real    0m10.306s
user    0m10.372s
sys 0m0.102s

Ruby 2.1.0-preview1
real    0m2.359s
user    0m2.328s
sys 0m0.012s

am working on semi-fancy benchmark/ips version for forthcoming pull request

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
