### ISSUE TITLE
Date#mon is slow

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#2838]
Date#mon is 20 times slower in rubinius 2.2.1 than mri 2.1.0

This seems to be the main reason that bm_cal.rb is 7 times slower in rubinius than mri.

test code:  ( date is diddled to avoid apparent memoization)

``` ruby
require 'date'

fi = Date.new(1926,6,1)

800_000.times do |i|
  (fi + i%2).mon
end
```

Semi-Fancy ips style benchmark exercising mon and other accessors to follow in forthcoming PR.

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
