### ISSUE TITLE
Intermittent segfault when running tests on rbx-2.2.1

### ISSUE THREAD

**Issue by benweint** [rubinius/rubinius#2841]
We're seeing occasional segfaults when running the test suites for the newrelic_rpm gem against rbx-2.2.1. They don't happen every time (or even most of the time).

I unfortunately don't have a reliable reproduction case yet, but here's an example stack trace:
https://gist.github.com/anonymous/50931a5aeee668acd219

I'll update here with more info if I figure out how to reproduce this.

```
$ rbx -v
rubinius 2.2.1 (2.1.0 3ed43137 2013-11-17 JI) [x86_64-linux-gnu]
$ uname -a
Linux <hostname redacted> 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by YorickPeterse** [comment]
Do these crashes still occur using Rubinius 2.5.2?

**Comment by YorickPeterse** [comment]
@benweint Have you been experiencing issues like these using more recent releases of Rubinius (e.g. 2.5.2)? With 2.5.3 released, is it possible to give that version a try to see how that works?

**Comment by benweint** [comment]
Hey @YorickPeterse!  Sorry for the lack of updates here.

We actually stopped running our full test suite (we still run our unit tests there, but not all of our functional tests) on rbx because of this and other similar issues (https://github.com/rubinius/rubinius/issues/3291, https://github.com/rubinius/rubinius/issues/3213), so I can't say for sure whether this has been fixed in recent versions or not.

I'll try to replicate this manually by running our tests in a loop if I get a chance soon and report back.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
