### ISSUE TITLE
FakeFS unusable with Rubinius and File.readable?()

### ISSUE THREAD

**Issue by ghost** [rubinius/rubinius#2872]
I think the current release of FakeFS might be completely unusable on rubinius.
i pulled this out of some code I'm working on: 
```ruby
require "fakefs"
dir = FakeFS::FileSystem.add ENV["HOME"]
file = FakeFS::FakeFile.new "hello.txt"
dir[file.name] = file
file.content = "quack"
File.readable?(file)
```

error:
```
An exception occurred running x.rb:

    Coercion error: (FakeFile name:"hello.txt" parent:"" size:5).to_str => String failed (TypeError)
```

it looks like bugs being likely are expected on rubinius from the comment here: 
https://github.com/defunkt/fakefs/issues/87#issuecomment-2483385

I find FakeFS really useful. is there anything it can do to work better on rubinius?

**Comment by brixen** [comment]
FakeFS assumes that it can overwrite or manipulate essential Ruby classes and methods. This works on MRI because those are a very thin veneer on top of C functions. That's not the case in Rubinius, where the classes and methods are Ruby classes and methods.

Using MRI is a good option if FakeFS is needed.
