### ISSUE TITLE
Random crash when using rbx

### ISSUE THREAD

**Issue by jarrettchisholm** [rubinius/rubinius#2969]
**The Rubinius version (rbx -v)**
`rubinius 2.2.5 (2.1.0 e543ba32 2014-02-08 JI) [x86_64-linux-gnu]`

**Your OS (uname -a)**
`Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux`

**Stack trace (preferably as a gist, since they're easier to read)**
https://gist.github.com/anonymous/a9ec1a86db95fbdf0a12

Unfortunately, I cannot reproduce this issue.  It happened on the second time I ran my ruby code, and hasn't happened since.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
