### ISSUE TITLE
Low performance for a Hello World in Puma

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#2979]
Mostly as a joke I put together a basic Ruby vs Node benchmark using the classic "Hello world" benchmark (the best benchmark). It can be found at https://gist.github.com/YorickPeterse/9555037.

All jokes aside, the relatively low performance of Rubinius Git compared to the other Rubies is interesting to say the least. I was expected it to be much closer to JRuby than it really is.

To measure what was really going on I modified the `start_ruby.sh` script so that it looks like the following:

``` bash
#!/usr/bin/env bash

echo 'Ruby version:'

ruby --version

export RACK_ENV=none
export RBXOPT='-Xprofile -Xprofiler.output=/tmp/profile.txt'

puma -e none -p 9292 -t 64:128
```

I then benchmarked the example using:

```
siege -c 10 -b -t 5s http://localhost:9292
```

The profiler output can be found here: https://gist.github.com/YorickPeterse/f68420ecbe213fe6d27b

I'll do some digging around to see what we can do to improve performance here.

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
