### ISSUE TITLE
Potential performance issue with C++/Ruby glue code?

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#2994]
I started doing a rewrite a the IO and File classes using FFI to wrap the syscalls. I quickly discovered that the FFI code, with equivalent error checking and locking, was far faster than the same code in C++. 

I am attaching two time profiler runs from Apple's Instruments which show the differences. To my eye, it just looks like the FFI code has way less of the interpreter to deal with. As we all know, "no code" is the fastest code.

The FFI IO & File can be found in my fork at https://github.com/chuckremes/rubinius

The runs are in a gist here: https://gist.github.com/chuckremes/6009174b2094d9f6a1f2

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
