### ISSUE TITLE
Crash during fetching the gem metada on 2.2.10/OSX 10.9.3.

### ISSUE THREAD

**Issue by keltia** [rubinius/rubinius#3087]
Hello, I was running "bundle" in several directories after installing 2.2.10 and it crashed during the fetch of metadata:

```
Fetching gem metadata from https://rubygems.org/.........
---------------------------------------------
CRASH: A fatal error has occurred.
```

    
    Backtrace:
    0   ruby                                0x000000010b898fc8 _ZN8rubiniusL12segv_handlerEi + 440
    1   libsystem_platform.dylib            0x00007fff8b68f5aa _sigtramp + 26
    2   ???                                 0x00007f8a29403b80 0x0 + 140231374289792
    3   ruby                                0x000000010b9b1acf _ZN8rubinius9utilities6thread6Thread10trampolineEPv + 15
    4   libsystem_pthread.dylib             0x00007fff8df12899 _pthread_body + 138
    5   libsystem_pthread.dylib             0x00007fff8df1272a _pthread_struct_init + 0
    6   libsystem_pthread.dylib             0x00007fff8df16fc9 thread_start + 13

Wrote full error report to: /Volumes/Users/roberto/.rbx/rubinius_last_error_3897
Run 'rbx report' to submit this crash report!

"rbx report" output in https://gist.github.com/202ea0e13dab7ec6b5d0

Please tell me if you need anything.

rubinius was compiled with clang 6.0 from Xcode 6beta3.

```
Apple LLVM version 6.0 (clang-600.0.38) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.2.0
Thread model: posix
```

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
