### ISSUE TITLE
Crash when using FFI and unjoined threads

### ISSUE THREAD

**Issue by Zapotek** [rubinius/rubinius#3124]
Hey guys,

Report: https://gist.github.com/anonymous/f039941ff2dcb3e5a8fe
Reproduce with:

```
require 'typhoeus'

t = []

20.times do |i|
    t << Thread.new do
        h = Typhoeus::Hydra.hydra
        r = Typhoeus::Request.new( 'http://google.com' )
        h.queue r
        h.run
    end
end

#t.each(&:join)
```

If you uncomment the last line the crash is avoided.

Cheers

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
