### ISSUE TITLE
JIT aborts in Calagator specs

### ISSUE THREAD

**Issue by jc00ke** [rubinius/rubinius#3201]
See https://gist.github.com/jc00ke/3654aee61260d05c42c5

```
$> uname -a
Linux maynard 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$> rbx -v
rubinius 2.3.0.n313 (2.1.0 21267107 2014-11-09 3.4.2 JI) [x86_64-linux-gnu]
```

**Comment by jasonrclark** [comment]
I might be seeing a similar problem when running newrelic_rpm's tests against rbx 2.5.0

```
  1) Error:
NewRelic::MetricSpecTest#test_initialize_can_take_a_non_string_name:
TypeError: Coercion error: #<#<Class:0xd1230>:0xd1234 @value="name">.to_str => String failed
    kernel/common/type.rb:36:in `coerce_to_failed'
    kernel/common/type.rb:26:in `execute_coerce_to'
    kernel/common/type.rb:19:in `coerce_to'
    kernel/common/kernel.rb:147:in `StringValue'
    kernel/common/string.rb:1543:in `replace'
    kernel/common/string.rb:615:in `to_s'
    /home/jenkins/workspace/RubyBranchUnitTest/BRANCH/rails40/RUBY_VERSION/rbx/jdk/jdk1.6/label/ruby-build/newrelic_rpm-3.9.9.321.branch/lib/new_relic/metric_spec.rb:15:in `initialize'
    /home/jenkins/workspace/RubyBranchUnitTest/BRANCH/rails40/RUBY_VERSION/rbx/jdk/jdk1.6/label/ruby-build/newrelic_rpm-3.9.9.321.branch/test/new_relic/metric_spec_test.rb:93:in `test_initialize_can_take_a_non_string_name'
```

The failure is sporadic, but one of the tests is https://github.com/newrelic/rpm/blob/master/test/new_relic/metric_spec_test.rb#L83-L97

Is there a way to disable the JIT apart from passing -X flags (i.e. ENV value or something)? Since this is happening in our test runner, it's not directly invoking rbx to pass those flags along at startup and I'm curious to see if it'll pass without the JIT.

~/source/newrelic/ruby_agent:uname -a
Darwin Soupy.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64

~/source/newrelic/ruby_agent:rbx -v
rubinius 2.5.0 (2.1.0 50777f41 2015-01-17 3.5.1 JI) [x86_64-darwin13.4.0]

**Comment by YorickPeterse** [comment]
@jasonrclark You can set the -X options in `RBXOPT`, e.g. `RBXOPT=-Xint`.

**Comment by jasonrclark** [comment]
Perfect, thanks @YorickPeterse!

Is there somewhere in the docs that I should have found it? I did search but failed to find reference to `RBXOPT`.

**Comment by YorickPeterse** [comment]
@jasonrclark Not as far as I know, it's currently cleverly hidden somewhere in the VM.

**Comment by jc00ke** [comment]
It's there when you run `-Xhelp`

```
int: Force the JIT to never turn on
```

It's a bit confusing though, IMO.

**Comment by jasonrclark** [comment]
FWIW, disabling the JIT did resolve those test failures for us, so we're good for the moment.

**Comment by brixen** [comment]
The Rubinius JIT is being rewritten from the ground up. To support this effort, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler infrastructure
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to work extensively on making the JIT extremely good.
