### ISSUE TITLE
LLVM ERROR: profiling_flag

### ISSUE THREAD

**Issue by gustavotemple** [rubinius/rubinius#3212]
When I try to use the parameter ```-Xjit.profile```, it is returned:
```LLVM ERROR: Could not resolve external global address: profiling_flag```

**Comment by fabioperez** [comment]
Any updates on this?

**Comment by brixen** [comment]
Note that the JIT and profiler interactions could result in inaccuracies, possibly due to LLVM optimizations changing how the JIT'd code would report (synthetic) method entry/exit.

We should be replacing the current profiler soon with something more accurate and independent of JIT'd vs non-JIT'd code.
