### ISSUE TITLE
Rubinius sometimes hangs in SEGV handler under dlopen

### ISSUE THREAD

**Issue by benweint** [rubinius/rubinius#3213]
We run our automated test suites against Rubinius (2.2.10 currently, planning to upgrade to 2.3.0 soon), and occasionally we see issues where Rubinius processes will get stuck and hang our tests indefinitely.

Digging into one of those issues today with GDB, I found the offending Rubinius process stuck under the backtraces seen in [this gist](https://gist.github.com/benweint/f8bedea59b1ab8216357).

The thing that stuck out there to me was this:

```
Thread 4 (Thread 0x7f32591a3700 (LWP 12267)):
#0  0x00007f32607972be in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x00007f326071c45b in _L_lock_9499 () from /lib64/libc.so.6
#2  0x00007f3260719996 in malloc () from /lib64/libc.so.6
#3  0x00007f3261a3fbad in _dl_map_object_deps () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f3261a45aa1 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#5  0x00007f3261a411b6 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#6  0x00007f3261a454fa in _dl_open () from /lib64/ld-linux-x86-64.so.2
#7  0x00007f32607c5e00 in do_dlopen () from /lib64/libc.so.6
#8  0x00007f3261a411b6 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#9  0x00007f32607c5f57 in __libc_dlopen_mode () from /lib64/libc.so.6
#10 0x00007f326079db15 in init () from /lib64/libc.so.6
#11 0x00007f32611dfd33 in pthread_once () from /lib64/libpthread.so.0
#12 0x00007f326079dc44 in backtrace () from /lib64/libc.so.6
#13 0x00000000006372f4 in rubinius::segv_handler (sig=11) at vm/signal.cpp:349
#14 <signal handler called>
#15 0x00007f3260715285 in malloc_consolidate () from /lib64/libc.so.6
```

It looks like Rubinius is calling `backtrace` from its SEGV handler, resulting in libc `dlopen`ing something, which in turn mallocs, which at last deadlocks on some internal lock within the malloc implementation.

This looks like an instance of [this issue](https://sourceware.org/bugzilla/show_bug.cgi?id=956), (since marked as a dup of [this bug](https://sourceware.org/bugzilla/show_bug.cgi?id=956)). From my reading, it sounds like the behavior of `backtrace` calling `dlopen` is unlikely to change.

In order to avoid hangs like this, would it be reasonable for `rubinius` to somehow trigger the relevant `dlopen` on startup to avoid it happening during the SEGV handler and deadlocking?

I unfortunately don't have a reliable repro case for this issue.

```
$ uname -a
Linux <hostname> 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
$ rbx -v
rubinius 2.2.10 (2.1.0 bf61ae2e 2014-06-27 JI) [x86_64-linux-gnu]
```

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
