### ISSUE TITLE
Symbol GC

### ISSUE THREAD

**Issue by jodosha** [rubinius/rubinius#3280]
Hello, do you have plans to support the new introduced feature in MRI regarding collectable symbols?

In order to protect applications from DoS attacks, we are forced to whitelist inputs, convert their keys to strings and to provide facilities we use tricks like _"indifferent access"_. This adds both development and runtime overhead.

I'm asking this specifically for Lotus. Supporting multiple Ruby VMs, with a different set of behaviors across versions is becoming really hard for us.

Thank you in advance.

**Comment by YorickPeterse** [comment]
Yes, symbols will be garbage collected in the near future, although there's no ETA for this change just yet.

**Comment by brixen** [comment]
@jodosha do you have a benchmark for the optimizations provided by Symbols?

Since the payload comes in as bytes, which are quite readily converted to String, not as Symbols, which do not exist external to a Ruby process, I'm curious about the overhead of converting to Symbols.

In particular, something must hand a bunch of bytes to some "function" which maps those bytes to an id (the Symbol value). That process requires 1) passing those bytes to a "hash" function, and then if that id exists, 2) comparing those bytes for identity with the bytes that previously hashed to that id. This is because (afaik) no one uses a guaranteed collision-free hash function. So, you pay this cost every time you convert some bytes to a Symbol that already exists, which seems like the common case in a web app.

Once you do have two Symbols, you get to compare them very cheaply for identity, so if the total comparisons * the cheaper comparison cost is less than the cost of creating the Symbols on every incoming request, you're ahead. Assuming, of course, that you don't have a more sophisticated runtime with a JIT that can elide unnecessary work in many varied circumstances, not just in comparing two values derived from a particular structure.

Anyway, I'm mostly curious how you're comparing these costs and what percentage of time they take in an actual application. And I'm explicitly trying to disentangle costs like MRI's GC costs, which appear to get conflated quite often with algorithmic costs unrelated to GC (or I should say, unrelated to historically very poor GC performance in MRI).

**Comment by brixen** [comment]
@jodosha BTW, a great way to avoid all this "indifferent Hash" nonsense is to let `String#==(Symbol)` and `Symbol#==(String)` be defined sensibly. Strings and Symbols are substitutable for each other in eg `#send` and all the introspection methods like `#instance_method(name)`. This sort of special cased behavior is silly in Ruby.

**Comment by jodosha** [comment]
@brixen I'm really, really sorry for this late reply, but I've missed the notification email in a burden of inbox filters. I apologize, thanks to @jc00ke to make me notice this.

### Indifferent access is :-1: 

It's a slow and hackish workaround. We receive a string hash but we want to be able to access with symbols too, because it's a common practice.

The solution that you suggested, requires monkey-patching, which is something that we don't want to do in Lotus.

### Strings and Symbols are kinda equivalent for perf

I've tried to compare two implementations of `Lotus::Utils::Attributes`: one uses strings and one symbols as keys of the wrapped `Hash`.

They have more or less the same perf results: https://gist.github.com/jodosha/8d8f6d81f305659189c6

### Take a side

So indifferent access is something to remove, and String and Symbol are equivalent. We should take a side and use only one of them.

Using symbols for access data a common pattern in Ruby libs, and we would love to keep this.
We want to ensure across the framework that symbol are used for options and accessing data.

The combination of those two principle above makes API brainless. Nobody should wonder if use a symbol or a string in a given context.

In Lotus, when you whitelist a param, or define an attribute you use symbols. It would be inconsistent to use strings to access data.

```ruby
class MyAction
  include Lotus::Action

  params do
    param :first_name
  end

  def call(params)
    params['first_name']
    params[:first_name] # this is consistent with the API above
  end
end
```

In the code above, the direct access to a parameter doesn't instantiate a new symbol, like the corresponding string usage.

### Improved perf

When you remove indifferent access, you get better numbers: https://gist.github.com/jodosha/7f16d332c65ec4dc0c52

In the bench above, I only have compared symbol vs indifferent access. I guess that string would have performed the same.

### Other security concerns

Imagine that we keep strings as keys for untrusted input. This makes Lotus compatible with Ruby 2.0+ mode. I'm still worried that some dev could symbolize it and make her or his application vulnerable.

### The future

Lotus is still a small framework in the Ruby Community, but Rails isn't. They just announced that supporting 2.2+ mode it will be a goal for their v5. IMHO, you should probably implement this feature anyway because of them.

**Comment by brixen** [comment]
@jodosha thanks for your detailed response. My concern is destroying this meme about Symbols being used as some sort of performance magic wand. There are costs to creating and maintaining (including GC'ing) Symbols, etc.

I'm not suggesting that you monkey patch to make Symbol and String comparable. I'm suggesting someone convince MRI/Ruby of that.

Rubinius will GC Symbols at some point.
