### ISSUE TITLE
Optimize loops

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3308]
It seems loops are not being optimized. See below:
```
~/P/n/master git:metadata-plugin ❯❯❯ rvm use rbx-2.5.2@noosfero     
Using /home/braulio/.rvm/gems/rbx-2.5.2 with gemset noosfero
~/P/n/master git:metadata-plugin ❯❯❯ time ruby -e "count = 0; while(count < 100000000); count = count + 1; end; puts count"     
100000000
ruby -e   44,98s user 0,05s system 100% cpu 44,685 total
~/P/n/master git:metadata-plugin ❯❯❯ rvm ruby-2.2.0@noosfero    
~/P/n/master git:metadata-plugin ❯❯❯ time ruby -e "count = 0; while(count < 100000000); count = count + 1; end; puts count"                                                              
100000000
ruby -e   2,66s user 0,00s system 99% cpu 2,663 total
```

**Comment by brixen** [comment]
@brauliobo the Rubinius JIT does not do on-stack-replacement (OSR). Essentially, you need to have the work load in a method that the JIT can compile. The method needs to exit so that the next invocation (after the JIT compiles it) can run the version the JIT created.

Please use issues for actionable things. In this case, you could look at the [rubinius-benchmark](https://github.com/rubinius/rubinius-benchmark) repository and improve a benchmark that shows a particular performance issue, then work on a PR that improves the performance here.

Also, consider using the Gitter chat (https://gitter.im/rubinius/rubinius) to ask questions about Rubinius.

**Comment by brauliobo** [comment]
@brixen thanks very much for the explanation! got 0,50s when putting the same code inside a method and ran it more than 3 times.

Sorry for dummy issue.

**Comment by brixen** [comment]
@brauliobo no worries! Visit us on Gitter if you want to chat more about stuff.
