### ISSUE TITLE
'scorched' gem fails miserably

### ISSUE THREAD

**Issue by mustmodify** [rubinius/rubinius#3309]
https://gist.github.com/mustmodify/ba6a3079517eda3ea049

    jw@logopolis:/projects/experiments/scorched-spike$ wc -l err.log
    5466 err.log
    jw@logopolis:/projects/experiments/scorched-spike$ cat err.log | sort | uniq | wc -l
    70

I hope to try to get an even simpler reproduction tomorrow. But who knows.

**Comment by mustmodify** [comment]
Works in MRI 2.1.4

**Comment by brixen** [comment]
`Scorched::Options` inherits from `Hash` and redefines all `Hash` methods except for a handful to be aliases of `Scorched::Options#to_hash`:

https://github.com/Wardrop/Scorched/blob/master/lib/scorched/options.rb#L6

In Rubinius, `Hash#merge!` calls `Hash#__store__`, which Scorched made an alias of `Scorched::Options#to_hash`, which calls `Hash#merge`, which calls `Hash#merge!`, which calls `Hash#__store__`, which calls `Scorched::Options#to_hash`, which calls `Hash#merge`...

In MRI, everything is a C function, and C functions call other C functions, that's why it works.

Rubinius doesn't support code like Scorched::Options. Please see [Liskov substitution principle](http://en.wikipedia.org/wiki/Liskov_substitution_principle) for an explanation.

**Comment by jemc** [comment]
@brixen beat me to the punch here with the explanation, but I'll chime in with a little extra:

@mustmodify, maybe you should hit them up with a pull request to use code that is a little more predictable - after seeing in the README for scorched that they tout the straightforwardness of their code and the virtue of eschewing magic for ease of understanding I think you should be able to sell them on it.

In an object-oriented language, it should be acceptable to subclass core classes like `Hash`.  In practice, we see it cause a ton of problems (see the recent psych issues, for example) which are always lurking but tend to be more visible on Rubinius.  This is mostly because the inner workings of these classes are hidden away in MRI and not very clearly specified or consistent in their design.  That makes it at the very least difficult for Rubinius to match, and in many cases downright undesirable to match where we would rather strive for consistency.
