### ISSUE TITLE
2.5.2 method sequence regression

### ISSUE THREAD

**Issue by jzakiya** [rubinius/rubinius#3314]
I seem to have found a regression between two equivalent method chains.

In MRI 2.2 and JRuby 1.7.19  1) is (slightly but consistently) faster  than 2).
In RBX 2.5.2  2) is significantly slower than 1), but 1) is supposed to be faster AND better coded.
Included is gist file of benchmarks to show difference in performance.

https://gist.github.com/jzakiya/f13e8e5e57a295a5c7b3

1) res.any? {|r| n%(r+p) == 0}

2) res.map {|r| n%(r+p)}.include? 0

**Comment by jc00ke** [comment]
@jzakiya can you provide an executable example? What's `res` supposed to be? A list of integers?

**Comment by YorickPeterse** [comment]
Also, please use https://github.com/evanphx/benchmark-ips instead of the regular Benchmark module as the latter doesn't take JIT warmups into account.

**Comment by jzakiya** [comment]
I changed the gist code to use benchmark-ips.
https://gist.github.com/jzakiya/f13e8e5e57a295a5c7b3

res is an array of integers (all numbers are integers).

If you load the file the benchmark will automatically run.

The only difference between primzpa? and primzpb? is the line indicated in my first post, pointed to in the code.  If you run the benchmark on MRI and JRuby you will see what I'm talking about.

**Comment by jzakiya** [comment]
Oh, I forgot to tell you this is for a 32-bit build.
I haven't tested in on a 64-bit system yet.

**Comment by brixen** [comment]
@jzakiya what do you mean by "regression" in your title? A regression in Rubinius is something broken or not performing in a later version relative to a previous version of Rubinius, not relative to MRI.

**Comment by jc00ke** [comment]
`Enumerable#any?` will go through [at most once](https://github.com/rubinius/rubinius/blob/b0825d87409b21ac80f123b5dbd8889df35a3e8c/kernel/common/enumerable.rb#L344-L351) where `Enumerable#map#include?` loops through up to 2x, once for the `#map` and up to once for `#include?` [(notice the `#each`)](https://github.com/rubinius/rubinius/blob/b0825d87409b21ac80f123b5dbd8889df35a3e8c/kernel/common/enumerable.rb#L740-L743).

I wouldn't expect for these 2 to perform the same.

**Comment by jzakiya** [comment]
Could you please post the benchmarks results you get.
On my system, using res.any? is about 1.5 times slower in both cases:
 
                     primzpa?          primzpb?
for prime1:  11.423584s     17.324351s
for prime2:  35.721200s     54.436080s

On MRI 2.2 and JRuby 1.7.19  primzpb? (using res.any?) is always slightly faster.
I can only conclude 2.5.2's implementation of array.any? is significantly different and slower.
Also, 2.5.2's benchmark times are slowest compared to MRI 2.2 and JRuby 1.7.19.
FYI.

**Comment by brixen** [comment]
@jzakiya we generally don't accept performance tickets unless they have a very narrow scope, a good benchmark, and a patch that specifically fixes the narrow scope. I'll attempt to explain the reasons for this policy:

1. Performance is a global property, but people usually look at it as a local property. Since the trade-off between space and time is fundamental in computation, it's possible to make one very small piece of code many times faster while making the system overall many times slower.
2. All performance tuning requires a completion criteria. When should we conclude we are finished optimizing the `res.any?` method? When we are as fast as MRI? Or twice as fast? How much effort should be spent making the method faster? Or should we be concerned at all about the performance? What if exploiting concurrency makes the performance of `res.any?` irrelevant? Then it doesn't matter how it performs relative to MRI, so we again don't have a completion criteria.

These questions can only be answered in a specific context. If the performance of `res.any?` is critical for your application (perhaps because that's all it does) then you have the context and you need to propose the patch.

Some things that you could do:

1. Improve a benchmark for this method in https://github.com/rubinius/rubinius-benchmark if a good one doesn't exist.
2. Investigate [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law).
3. Investigate your app's performance by leveraging the full concurrency support that Rubinius provides. Is the bottleneck still an issue when exploiting concurrency?
4. Investigate a systemic improvement (for example, in the JIT) that addresses this performance issue by making the performance of everything faster. (_A rising tide raises all boats_ approach.)
5. Use the [Rubinius::Metrics](http://rubini.us/2015/01/05/rubinius-metrics-meets-influxdb-part2/) to investigate your app's performance holistically.
