### ISSUE TITLE
Cleaning rbx 2.2.10 failed on FreeBSD 10.1

### ISSUE THREAD

**Issue by dt1973** [rubinius/rubinius#3336]
```
# ruby-install rbx
...
>>> Cleaning rubinius 2.2.10 ...
rake aborted!
Errno::ENOENT: No such file or directory - /usr/local/src/rubinius-2.2.10/vendor/llvm/Release/bin/llvm-config
(eval):201:in `block in load'
(eval):1:in `load'
Tasks: TOP => clean => vm:clean
(See full trace by running task with --trace)
!!! Cleaning rbx 2.2.10 failed!
```

**Comment by YorickPeterse** [comment]
You'll need to have LLVM installed (and `llvm-config` in your `$PATH`) in order to install Rubinius (unless you disable LLVM support during compilation). If `llvm-config` is called something differently (e.g. `llvm-config3.4`) you can use the `--llvm-config` option to customize the path. In your case:

    ruby-install rbx -- --llvm-config=path/to/alternative/llvm-config

Also, please try Rubinius 2.5.2 as 2.2.10 is quite old by now, you either need to update ruby-install or run `ruby-install rbx 2.5.2`. Closing this since this is, as far as I can tell, not really a bug with Rubinius. Feel free to re-open if needed.

**Comment by dt1973** [comment]
Thanks for the clarification. Have a great weekend!
