### ISSUE TITLE
Cannot convert ActiveSupport::HashWithIndifferentAccess to/from YAML with psych

### ISSUE THREAD

**Issue by pH14** [rubinius/rubinius#3337]
This seems to be a continuation of this error : https://github.com/rubinius/rubinius/issues/3279

I'm running a rails 4.2.0 app with rbx 2.5.0 / 2.5.2, and I keep getting that error with any version of psych > 2.0.9.

An app to demo this with (no test case yet, 'cause I don't really know what's going on) : https://github.com/pH14/demo-app-with-authpwn To reproduce the error, clone that repo, then the normal rails stuff (bundle install / rake db:migrate db:seed / rails s) to get it running, then try to log in (foo@bar.com, asdf) and it'll throw the error.

If there are any obvious temporary workarounds that'd be great for the small bit that I need this to work for.

**Comment by jemc** [comment]
I'm not in a position to run your app and reproduce right now, but we can get you meaningful help quicker if you show the full traceback you get and also the contents of your `Gemfile.lock`.

**Comment by pH14** [comment]
Yep, somehow forgot the traceback.

Traceback: https://gist.github.com/pH14/59febddcd066b3115cbc
Gemfile.lock: https://github.com/pH14/demo-app-with-authpwn/blob/master/Gemfile.lock

**Comment by jemc** [comment]
There are still issues with latest psych and `ActiveSupport::HashWithIndifferentAccess` because it is a subclass of `Hash`.

See https://github.com/tenderlove/psych/issues/220 and https://github.com/tenderlove/psych/issues/216

So, the best workaround would be to make sure you convert your `ActiveSupport::HashWithIndifferentAccess` to a `Hash` (or some other representation) before converting it to YAML.

I'm changing the title of the issue to be a bit more informative now that we've identified out the root of the problem.

**Comment by pH14** [comment]
Aright thanks for that info jemc, that's helpful to figure out a next step.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
