### ISSUE TITLE
ruby-gpgme failure __gpgme_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.

### ISSUE THREAD

**Issue by vulpino** [rubinius/rubinius#3353]
When running the code
```ruby
GPGME::Engine.home_dir="#{Dir.getwd}/gpghome"
```
at the same time in multiple threads (using `Thread.new`) Rubinius (but not MRI) fails, passing the error:
```
ruby: ath.c:109: _gpgme_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.
```
And, further down in the backtrace:
```
0x7f9b04e736b0: capi:gpgme_get_engine_info at vm/capi/module.cpp
GPGME::Engine.info in /home/travis/.rvm/gems/rbx-2.5.2/gems/gpgme-2.0.8/lib/gpgme/engine.rb:37 (+12)
GPGME::Engine.home_dir= in /home/travis/.rvm/gems/rbx-2.5.2/gems/gpgme-2.0.8/lib/gpgme/engine.rb:71 (+3)
```
I've created an [example repository](https://github.com/vulpino/rubinius-gpgme-fail) and [Travis-CI build](https://travis-ci.org/vulpino/rubinius-gpgme-fail/builds/53978796) to illustrate the issue. The Travis-CI build specifies the RBX version (`rbx-2.5.2`) but in other projects I have also observed it failing on 2.2.10.

GPGme [says it is threadsafe](https://www.gnupg.org/documentation/manuals/gpgme/Multi-Threading.html) provided gpgme_check_version is called before anything else, but it is called when `require 'gpgme'` is, so I'm unsure what the issue is otherwise.

**Comment by YorickPeterse** [comment]
I'm able to reproduce this using the latest master version of Rbx. GDB logs: https://gist.github.com/YorickPeterse/434e361be76e37fb34ac

**Comment by brixen** [comment]
Whether GPGme is thread-safe or not (I'm not deciding either way) isn't dispositive here. You're calling into C-API code concurrently and C-API code is absolutely not thread safe by default. The assertion failure is in GPGme code and is likely caused by passing a bad value in.

Running with `rbx -Xcapi.lock -v test.rb` produces:

```
$ rbx -Xcapi.lock -v test.rb
rubinius 2.5.7.c55 (2.1.0 14b60c27 2015-07-14 3.5.1 JI) [x86_64-darwin14.4.0]
mkdir: gpghome: File exists
```

You can use `-Xcapi.lock` to add a global lock around entering the C-API, which mimics MRI's global lock to some extent. However, this isn't going to provide efficient multi-core behavior. Instead, I suggest making your C-ext thread safe.
