### ISSUE TITLE
compile fails on oniguruma

### ISSUE THREAD

**Issue by tukanos** [rubinius/rubinius#3400]
I'm trying to compile rubinius 2.5.3 on windows.  
I'm building it with:
ruby 2.0.0p645 (2015-04-13) [i386-mingw32]
gcc\g++ - gcc (rubenvb-4.7.2-release) 4.7.2 => 686-w64-mingw32

The compile fails on oniguruma:

the rake install --trace produces:
1: LDSHARED enc/trans/big5.so
enc/trans/artifacts/big5.c.o: In function `Init_big5':
C:\prg_build_env\ruby\rubinius-2.5.3\vendor\oniguruma/enc/trans/big5.c:68953: un
defined reference to`rb_register_transcoder'
C:\prg_build_env\ruby\rubinius-2.5.3\vendor\oniguruma/enc/trans/big5.c:68954: un
defined reference to `rb_register_transcoder'
C:\prg_build_env\ruby\rubinius-2.5.3\vendor\oniguruma/enc/trans/big5.c:68955: un
defined reference to`rb_register_transcoder'
C:\prg_build_env\ruby\rubinius-2.5.3\vendor\oniguruma/enc/trans/big5.c:68956: un
defined reference to `rb_register_transcoder'
C:\prg_build_env\ruby\rubinius-2.5.3\vendor\oniguruma/enc/trans/big5.c:68957: un
defined reference to`rb_register_transcoder'
enc/trans/artifacts/big5.c.o:C:\prg_build_env\ruby\rubinius-2.5.3\vendor\oniguru
ma/enc/trans/big5.c:68958: more undefined references to `rb_register_transcoder'
 follow
collect2.exe: error: ld returned 1 exit status
Error: g++ -shared enc/trans/artifacts/big5.c.o -o enc/trans/big5.so
rake aborted!
Error compiling

Do you have any idea how to solve the "undefined reference error?  (I have found the rb_register_transcoder in the MRI - http://rxr.whitequark.org/mri/source/transcode.c?v=1.9.2-p381#199)

**Comment by YorickPeterse** [comment]
Windows isn't supported yet sadly.

**Comment by brixen** [comment]
@tukanos at one point, I had the full VM compiling with mingw-w64, but I needed to fix symbol export to be able to link C exts. It probably won't be too much work to get it compiling again, but we will only support mingw-w64 or clang/clang++ on Windows because of licensing problems involving mingw (unless that situation has changed significantly in the past couple years).

If you want to get Rubinius on Windows now, I'd suggest trying to build in a Cygwin environment as those issues would likely be fixable quickly.

**Comment by tukanos** [comment]
@YorickPeterse: Yes, I know.  I wanted to make a splash because from what I have read from the pages and code it doesn't look like big issue.  I'm working now for a company that has windows only environment (except maybe some very few servers).  As I'm forced to live in the windows only environment I like to take the stuff from *nix world.

@brixen: I'm not in a hurry.  I thought I could get it running via cygwin or some virtualization like docker or vmware/virtualbox, but that is a backup plan if things won't work for a long time.

I wanted to have a native build to see if I could build a personal project on rubinius & windows.  I'm prepared for some fix obstacles on the way, but I must admit at this point my knowledge of rubinius and its environment is rather limited.

I saw in the source code that LLVM is restred to 3-3.5 version.  Are there any issues with the versions 3.6 & 3.7?

>we will only support mingw-w64 or clang/clang++ on Windows
I don't have any problems with that :).  I want to learn from the building process about rubinius and its workings.

The mingw licencing doesn't look to bad for the 4.0 a newer. (https://sourceforge.net/p/mingw/mingw-org-wsl/ci/21762bb4a1bd0c88c38eead03f59e8d994349e83/tree/LICENSE or full version at http://www.mingw.org/license)
As for the licensing of mingw

One more question about these requirements:
What is the reason for them?  I think I got suitable windows equivalents but I wanted to know more about the specifics ->
    GNU Bison
    ZLib
    pthread - The pthread library should be installed by your operating system -> (this is probably for the proper parallel rubinius support)
    editline when using newer versions of LLVM

Thank you

**Comment by YorickPeterse** [comment]
> I saw in the source code that LLVM is restred to 3-3.5 version. Are there any issues with the versions 3.6 & 3.7?

LLVM >= 3.6 removed the old JIT API that we rely on, replacing it with a new API called MCJIT. We don't support this new API yet, though work is under way (#3367).

> GNU Bison

This is used for the parser, which we largely port from MRI.

> ZLib

Used for the zlib interface provided by Ruby and possibly other things.

> pthread - The pthread library should be installed by your operating system -> (this is probably for the proper parallel rubinius support)

Rubinius' thread system relies on pthread, any POSIX compatible system will probably have this. We can't swap it out for something else as far as I'm aware of.

> editline when using newer versions of LLVM

LLVM for some arcane reason requires editline/readline when compiling. Since we don't ship LLVM ourselves any more I'm not sure if we still need this to be installed.

**Comment by brixen** [comment]
Rubinius is unlikely to ever support compiling natively on Windows.
