### ISSUE TITLE
Syntax error using def as argument

### ISSUE THREAD

**Issue by heftig** [rubinius/rubinius#3450]
`private(def foo; bar.each do; end; end)` works in both MRI 2.2.2 and Rubinius 2.5.7.

`private def foo; bar.each do; end; end` works in MRI but causes a syntax error in Rubinius.

**Comment by jemc** [comment]
I filed this in the rubinius-melbourne repo a while ago: https://github.com/rubinius/rubinius-melbourne/issues/21

Still waiting on some feedback from @brixen on how he wants to proceed.

**Comment by brixen** [comment]
I was holding off to update for the 2.2 grammar, since it adds eg `"abc#{d}":` for interpolated Symbols. Unless we know of any breaking 2.2 syntax changes, we could update the parser before officially switching to 2.2 compat.

On the other hand, we've got a lot of the 2.2 code changes in the 2.2 branch, so maybe we should just flip the switch.

**Comment by jemc** [comment]
I think this syntax was possible in (at least some versions of) 2.1, so it's not necessarily a 2.2 thing.  However, it would be silly to import and adapt to the changes in the MRI grammar twice in such a short period of time, so if we do import it, it does make sense to import that latest grammar.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
