### ISSUE TITLE
Question: Is HLVM suitable for Rubinius?

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3454]
I recently noticed and read that using LLVM doesn't really help to get performance on dynamic languages like Ruby, as you (e.g. Rubinius) have to do the hard work to optimize the code.

Then I've found http://www.ffconsultancy.com/ocaml/hlvm. Maybe it or something similar may be used for rubinius?

Sorry for the newbie question.

**Comment by brixen** [comment]
@brauliobo LLVM does a lot to help optimize performance, but it's not magic. We still have to translate Ruby code into LLVM IR so that LLVM can emit machine code.

Here's a simple benchmark I was looking at last night with times for MRI 2.2 and Rubinius 2.5.7 on my machine:

```ruby
# scripts/bm_array_aref.rb
require 'benchmark/ips'

def work(array, index)
  array[index]
end

Benchmark.ips do |x|
  x.report("Array#[]") { work [1, 2, 3, 4], 2 }
end
```
Here are results with MRI 2.2.2
```
$ ruby -v scripts/bm_array_aref.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Calculating -------------------------------------
            Array#[]    97.351k i/100ms
-------------------------------------------------
            Array#[]      2.655M (± 9.2%) i/s -     13.240M
```
And results on Rubinius 2.5.7
```
$ ruby -v scripts/bm_array_aref.rb
rubinius 2.5.7 (2.1.0 d4fdeaad 2015-06-16 3.5.1 JI) [x86_64-darwin14.4.0]
Calculating -------------------------------------
            Array#[]   122.813k i/100ms
-------------------------------------------------
            Array#[]      4.364M (± 6.8%) i/s -     21.738M
```
As you can see, the JIT helps. We still have a lot of work to do to improve the JIT, however.

**Comment by brauliobo** [comment]
@brixen 
Nice! http://jruby.org/bench9000/ benchmarks shows rubinius 11% faster than on MRI 2.2.2.
Still on rails it is not as performant as MRI.

Did you take a look at HLVM? Maybe it could ease the work to translate to LLVM IR.
