### ISSUE TITLE
Immix crash in the AWS grinder

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3466]
This time running the script from #3461 resulted in a crash in Immix: https://gist.github.com/YorickPeterse/959032063fa19c83e230

Note the last bit of the GDB log, it seems the variable Immix is trying to GC is a NULL pointer. While the code below it checks for NULL pointers (https://github.com/rubinius/rubinius/blob/aa7814191b3cff9e20169361f34ee2c34d9d6345/vm/gc/gc.cpp#L367) it appears to crash before the process can even reach that code.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
