### ISSUE TITLE
rbx 2.5.8 + celluloid (?) + rspec

### ISSUE THREAD

**Issue by kayakyakr** [rubinius/rubinius#3496]
I'm getting a segfault with "invalid handle usage detected" when I'm trying to run tests. Will be chasing down the exact cause today, but I figured I'd open an issue here while I looked at narrowing it down.

The stack dump and the bundle list is here:
https://gist.github.com/kayakyakr/bce313661c3fc4bd6890

Peculiarly, it does not fail with an error if I only run a single file. Only errors on a full suite.

**Comment by brixen** [comment]
@kayakyakr do you know if it happens on 2.5.7, and is it possible for us to run your tests?

**Comment by kayakyakr** [comment]
I get a segfault on 2.5.7. Updated the gist to show the segfault.

I don't think you can run the tests. I'm going to narrow down what is causing the failures and see if I can recreate it in a clean project.

**Comment by kayakyakr** [comment]
It's definitely something to do with sucker punch/celluloid workers in the testing environment, but it seems to cause general instability instead of outright, repeatable crashes.

**Comment by brixen** [comment]
@kayakyakr can you elaborate on "general instability instead of outright, repeatable crashes"? If it appears to be Celluloid related, we could try making a Celluloid torture test that doesn't involve your app and looking at that.

**Comment by kayakyakr** [comment]
I'm actually leaning away from it being celluloid based now. A bunch of our tests (and some of our codebase) were written in terrible looping code and it seems like the instability is based in any of that code that is saving within one of those loops. I'm currently in the process of switching all of that over to batch saves, and the stability of the suite is shooting up rapidly.

Using Mongoid 4 as the ODM.

**Comment by brixen** [comment]
@kayakyakr ah, this is interesting. What's the state of thread-safety in Mongoid these days? It's been a huge issue in the past.

**Comment by kayakyakr** [comment]
I'm not sure. None of this should be running in a secondary thread, though, now that we've changed a bunch of tests.

**Comment by washu** [comment]
Brixen 
Time#plus_without_duration
that old friend again .. could this possibly lead to a jit issue?

**Comment by YorickPeterse** [comment]
@washu What specifically are you talking about?

**Comment by washu** [comment]
Time#plus_duration ends up getting nil somewhere in the jit in a threaded condition .. all runs back to activesupport timezone code getting jit'd in the case i was examining with brixen. 
He has my full dumps of when it happened to me. around feb of this year.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
