### ISSUE TITLE
`rubinius` has fall into cyclic method call loop, when calling `force_encoding`

### ISSUE THREAD

**Issue by majioa** [rubinius/rubinius#3498]
Hello.

It seems the `rubinius` has fall into cyclic method call loop, when calling `force_encoding` from within redefined `upcase` method of `String` class, because it calls `upcase` again inside of it, while original `mri` do not. So the part of stacktrace is shewn below:

    SystemStackError (SystemStackError)
         kernel/common/hash.rb:133:in `allocate'
         kernel/common/hash.rb:128:in `new_from_literal'
         ./lib/rdoba/mixin.rb:184:in `__rdoba_mixin_upcase__'
         (eval):1:in `upcase'
         kernel/common/type.rb:375:in `try_convert_to_encoding'
         kernel/common/encoding.rb:546:in `find'
         kernel/common/type.rb:359:in `coerce_to_encoding'
         kernel/common/string.rb:978:in `force_encoding'
         ./lib/rdoba/mixin.rb:196:in `__rdoba_mixin_changecase__'
         ./lib/rdoba/mixin.rb:185:in `__rdoba_mixin_upcase__'
        (eval):1:in `upcase'

And the code:
    
    def upcase
       ...
        self.dup.force_encoding( 'ASCII-8BIT' )
       ....

**Comment by YorickPeterse** [comment]
The sole reason this works in MRI is because it does everything in C, bypassing whatever methods you redefined. We use `upcase` to determine what `Encoding` constant is mapped to a given string value (e.g. `Encoding::UTF_8` being mapped to "UTF-8").

There's currently no way around this, and I don't think we'll provide one any time soon. This particular problem can occur for any method we define in Ruby. In other words, overwriting core methods is something that should be done with extreme care. Some similar problems:

* https://github.com/rubinius/rubinius/issues/3373
* https://github.com/rubinius/rubinius/issues/3050
