### ISSUE TITLE
rbx-2.5.8 crash with Postgres and SQLite

### ISSUE THREAD

**Issue by korobkov** [rubinius/rubinius#3500]
I've such a rather strange crash (SIGSEGV) on rbx-2.5.8:

1) For one of my projects (https://travis-ci.org/korobkov/perth)
it fails only with Postgres (via `pg` gem): https://travis-ci.org/korobkov/perth/jobs/78735784
but works well with SQLite (via `sqlite3` gem): https://travis-ci.org/korobkov/perth/jobs/78735787

2) But for another my project (https://travis-ci.org/korobkov/fremantle)
it fails both with Postgres (via `pg` gem): https://travis-ci.org/korobkov/fremantle/jobs/78737238
and with SQLite (via `sqlite3` gem): https://travis-ci.org/korobkov/fremantle/jobs/78737241

For comparison: the same project code being tested on different other ruby implementations (MRI 2.1 and 2.2) works pretty well (you could see green marks on their tests in Travis).

Both projects are Free Software and fully available in source to clone and reproduce the issue.
I hope these backtraces will be useful for searching and fixing the issue.
I'm also open and could provide some additional debug info should you say it's needed.

**Comment by sethk** [comment]
I'm seeing a very similar crash trace in my Rails app. It seems to be related to define_non_cyclic_method or autosave_association in active record. Trying to narrow it down…

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
