### ISSUE TITLE
Rubinious build fail on OS X 10.10.5

### ISSUE THREAD

**Issue by franklinyu** [rubinius/rubinius#3507]
I install with
```sh
brew remove llvm
brew install llvm35
rvm install rbx -- --llvm-config /usr/local/opt/llvm35/bin/llvm-config-3.5
```
and it gives [some error](http://pastebin.com/DFhz8bmZ).

Dump excerpts that I believe are important:
```text
vm/llvm/disassembler.cpp:77:27: error: allocating an object of abstract class type 'rubinius::JITMemoryObject'
      memory_object = new JITMemoryObject((const uint8_t*)buffer, (uint64_t) size);
                          ^
vm/llvm/disassembler.cpp:115:62: error: no member named 'getInstrInfo' in 'llvm::TargetMachine'
    const llvm::TargetInstrInfo* inst_info = target_machine->getInstrInfo();
                                             ~~~~~~~~~~~~~~  ^
vm/llvm/disassembler.cpp:124:39: error: no viable conversion from 'const rubinius::JITMemoryObject' to 'ArrayRef<uint8_t>'
                                      *memory_object, instruction_pointer,
                                      ^~~~~~~~~~~~~~
````

**Comment by YorickPeterse** [comment]
Your build configuration still seems to be using whatever system version of LLVM you have installed (note the error paths poiting to `/usr/local/opt/llvm` instead of `/usr/local/opt/llvm35`. It's likely you're not passing the options to `./configure` correctly. However, we can't help with RVM related problems, so please try compiling from source to see if that works.

**Comment by franklinyu** [comment]
Thank you for your kind help. I have already found the solution to my problem at rvm/rvm#3513. Perhaps buggy RVM is to blame.
