### ISSUE TITLE
2.7 is missing gems

### ISSUE THREAD

**Issue by heftig** [rubinius/rubinius#3537]
The following gems were in 2.6 and are missing in 2.7:
```
vendor/cache/aws-sdk-2.2.4.gem
vendor/cache/aws-sdk-core-2.2.4.gem
vendor/cache/aws-sdk-resources-2.2.4.gem
vendor/cache/jmespath-1.1.3.gem
vendor/cache/rubinius-bridge-1.1.0.gem
```
At least `jmespath` is preventing the build.
```
Some gems seem to be missing from your vendor/cache directory.
Could not find jmespath-1.1.3 in any of the sources
```

**Comment by brixen** [comment]
@heftig sorry, it's a bit messy right now as I try getting the deploy automated. I'd suggest not watching the tag, but wait until there's actually a tarball. The tag is a candidate release, but until it is "deployed" (ie there is a tarball available), the process isn't complete.

Since there is an entire process that needs to run and some of it has inherent races (ie we can't schedule when a Travis instance will spin up or when one will finish relative to another), we'll need to figure out what to use as a signaling mechanism.

As for the gems in this case, I probably need to remove the aws-sdk remnants now that we're using plain Bash.

**Comment by heftig** [comment]
You mean the list at http://rubinius.com/downloads/ ? Alright.

**Comment by brixen** [comment]
@heftig no, the first is right, it should redirect to http://rubinius-releases-rubinius-com.s3-us-west-2.amazonaws.com. Also, you'll want to update to http://releases.rubinius.com.

Unfortunately, as I said above, we need a better signaling mechanism because even building the release tar is subject to the races I mentioned. I think this week it will probably be reliable to check that the tarball is there, but it's not yet, since building the tarball may succeed when another step fails.

What do you think we could use as the signal? Maybe updating the website release?

**Comment by heftig** [comment]
I can't tell you what kind of signalling Travis supports, sorry.

**Comment by brixen** [comment]
@heftig it's not what kind Travis supports but what we choose. For instance, I can have a webhook that gets a payload when the tag is pushed and polls until all the expected artifacts are available and then updates the website.

But, maybe it's enough to just use the tarball. If the tarball is there, that's sufficient. If there's an issue, we'll just release again, since all it takes is pushing a tag. If I'd done that starting at 2.6, we'd be on like 2.30 right now because it took a bit to work out the deploy automation. It's pretty well settled now.

Go ahead and build if you see a tarball available and if we are having serious problems with that, we'll revisit. Sound good?

**Comment by heftig** [comment]
If you don't mind version proliferation, that's fine.

**Comment by brixen** [comment]
@heftig I don't think it will proliferate releases independent of actually pushing out much finer-grained work. For instance, if the just-pushed 2.7 successfully deploys, it will contain the rubygems update to 2.5.1. That's all we need for a release. If there's anything we can do to help improve your automation around building binaries (besides making the dependencies to build *way* simpler), let us know.
