### ISSUE TITLE
Object#inspect's address should not be Object#object_id

### ISSUE THREAD

**Issue by andre-richter** [rubinius/rubinius#3561]
AFAICS rubinius's #inspect is realized via `self.object_id.to_s(16)` in order to get the object's address.
MRI presents two different addresses.
Is this of any concern?

```ruby
#!/usr/bin/env ruby
o = Object.new
puts o.inspect
puts "#<Object:0x" + o.object_id.to_s(16) + ">" # rubinius style inspect implementation
```

```bash
ruby:
#<Object:0x007f8213970288>
#<Object:0x3fc109cb8144>
```

```bash
rubinius:
#<Object:0x1dc>
#<Object:0x1dc>
```

**Comment by YorickPeterse** [comment]
Is there any code that depends on the exact formatting of `#inspect`? Considering it's mostly for debugging purposes and the address itself is rather pointless I'm not sure if this is really worth spending time on.

**Comment by brixen** [comment]
@andre-richter in Rubinius, objects can move in memory and there is no valid way to talk about an object's "address".

Rubinius does not guarantee to have the same `#inspect` output as Ruby, nor do we have the same contents of other messages, like those in exceptions. Ruby's text is often less useful than it could be and programs that expect to have exactly Ruby's text are unnecessarily brittle and prevent us from providing better facilities and useful messages to developers.

Note that from now on, I'm going to uniformly use "Ruby" to refer to Matz's language and implementation, there is no useful distinction between those two things and "Ruby" is well-understood. Rubinius and Ruby are two different things. Sometimes Rubinius is compatible with Ruby and sometimes it is not.

Unfortunately, "compatible" is itself a difficult to define concept, so this is the working definition: "Rubinius is _compatible_ with Ruby to the extent that developers of Ruby programs that wish to use Rubinius are able to do so without "unreasonable" additional work." There are practices that some Ruby developers use that we don't support, like arbitrarily over-riding Ruby core class methods (without respecting LSP) because the Rubinius core library is written in Ruby.

In the case of something like `#inspect` formatting, the programs that try to parse this content (or eg exception messages) are doing so because proper access to that information in a programatic way is not available. Rubinius supports adding accessors or other methods to provide that information, rather than supporting Ruby's choice of formatting and textual content.

I'll get this information into the Rubinius book ASAP. For now, you can refer people with questions not this comment.
