### ISSUE TITLE
GitLab test suite segfaults Rubinius

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3585]
Running the gitlab-ce test suite using `bundle exec rspec -fp spec/models` results in the following segfault (from the logs): https://gist.github.com/YorickPeterse/f066b9427086fd8a1902

GDB output: https://gist.github.com/YorickPeterse/0c3bb0442c4e51acd046

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
