### ISSUE TITLE
BasicObject#instance_exec does not allow return in lambda

### ISSUE THREAD

**Issue by karloku** [rubinius/rubinius#3588]
The following code raises LocalJumpError.

```
irb(main):001:0> p = -> { return 1 }
=> #<Proc:0x15ec@(irb):1 (lambda)>
irb(main):002:0> instance_exec &p
LocalJumpError: unexpected return
    from (irb):1
    from kernel/common/eval.rb:104:in `instance_exec'
```

While MRI 2.2.2 can pass

```
irb(main):001:0> p = -> { return 1 }
=> #<Proc:0x007fef745f8140@(irb):1 (lambda)>
irb(main):002:0> instance_exec &p
=> 1
```

**Comment by akhramov** [comment]
I am not a contributor of Rubinius, just hanging around.

I am wondering if there's a way to reproduce this issue through MSpec. The problem is we cannot achieve LocalJumpError inside a `lambda { ... }.should` piece because it will simply return from upper lambda.

BTW, let me examine my sixth sense regarding a ticket. The problem lies [here](https://github.com/rubinius/rubinius/blob/4eec62a07d6b3cbdfee3c4ce0b6e6a18498641a4/vm/builtin/block_environment.cpp#L554). We need to add cIsLambda to flags in order to distinguish lambda and proc calls... ryyyt?

**Comment by akhramov** [comment]
I am not a contributor of Rubinius, just hanging around.

I am wondering if there's a way to reproduce this issue through MSpec. The problem is we cannot achieve LocalJumpError inside a `lambda { ... }.should` piece because it will simply return from upper lambda.

BTW, let me examine my sixth sense regarding a ticket. The problem lies [here](https://github.com/rubinius/rubinius/blob/4eec62a07d6b3cbdfee3c4ce0b6e6a18498641a4/vm/builtin/block_environment.cpp#L554). We need to add cIsLambda to flags in order to distinguish lambda and proc calls... ryyyt?

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
