### ISSUE TITLE
Rubinius' front page is extremely vague about what it actually is

### ISSUE THREAD

**Issue by Ivoz** [rubinius/rubinius#3596]
It is great at describing its goals, its vision, how it can help and enable humanity and communities, even its moral values.

However it is not very good at all at describing what it is exactly, practically, that "rubinius 3.X" the piece of software, does and is. What people do with it. For which practical reasons they tend to install and run it. Someone completely new, interested in Rubinius, coming to the website for the first time, might get a little confused and lost. I know I did.

In contrast, the current README.md of the project in its source code tree does a *far* better job at this. OK, you're a general programming language VM-type thing and your main effort is a JIT'ed Ruby implementation, right?

Unfortunately there is no link on the homepage to Rubinius' main github project page. Not even under the 'source code' link at the bottom. The home page also links to "Rubinius Console" which is now non-existent.

**Comment by brixen** [comment]
@Ivoz thanks for opening this issue. We're in a bit of a transition with the website and documentation.

I've opened https://github.com/rubinius/rubinius.github.io/issues/57 to add a link to the GitHub source on the website.

I've opened https://github.com/rubinius/rubinius-book/issues/1 for the Rubinius book to address your other points. The Rubinius book is where all this content will go and we'll link to it from both the README here and from the website.

For some reason, Rubinius Console directory was under my user. I've transferred it to the Rubinius org, so that should be fixed.

Please track those other issues. I'll close this because there's nothing to do in this repo for them.
