### ISSUE TITLE
A safe navigation operator

### ISSUE THREAD

**Issue by majioa** [rubinius/rubinius#3629]
## Problem

The exception is thrown in the code:

> SyntaxError: syntax error, unexpected '.': /home/travis/build/znamenica/bukovina/lib/bukovina/parsers/name.rb:51:42

## How to Reproduce

The problem is risen up because of new operator of ruby (mri) 2.3.0 isn't exist in  rubinius:

 > [A safe navigation operator (so-called lonely operator) &., which already exists in C#, Groovy, and Swift, is introduced to ease nil handling as obj&.foo. Array#dig and Hash#dig are also added. Note that this behaves like try! of Active Support, which specially handles only nil.][1]

The problem present in both 2.11 and 3.19 versions.

  [1]: https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/

**Comment by brixen** [comment]
@majioa this is an issue for the parser and compiler, and unlikely to need any changes in Rubinius itself. Could you please re-open the issue here https://github.com/rubinius/rubinius-code/issues ?

Note that Rubinius provides a Ruby-compatibility version in the `-v` output. For example:

```
rubinius 3.14 (2.2.2 a7ba16db 2016-01-28 3.5.1) [x86_64-darwin13.4.0]
```

 Currently, that is 2.2.2, so this operator won't be supported until that compatibility version is 2.3.0.

**Comment by swrobel** [comment]
This appears to have been implemented at some point. Working for me on `rubinius 3.65 (2.3.1 eb399e63 2016-11-01 3.8.1) [x86_64-darwin15.6.0]`

**Comment by brixen** [comment]
@swrobel yes, it's implemented. It came with the parser + compiler updates for Ruby 2.3 compatibility around July (see Melbourne version 3.7, AST version 3.7).
