### ISSUE TITLE
have_func for Ruby C API always returns false

### ISSUE THREAD

**Issue by jkr2255** [rubinius/rubinius#3637]
## Problem

In writing C extension, I wanted to use `rb_big_pack`, which is [Recently added to Rubinius](https://github.com/rubinius/rubinius/issues/3089).

So, write `have_func('rb_big_pack')` in `extconf.rb` and ran, It reported `checking for rb_big_pack ... no`.

Not only this function, other functions such as `rb_p` fail to check existence in mkmf.

### Investigation

In CRuby, C source code generated by mkmf is compiled and linked against static Ruby library to check properly.

On the other hand, Rubinius [lacks static library](https://github.com/rubinius/rubinius/issues/1043), so linking doesn't resolve dependency.

## How to Reproduce

```rb:extconf.rb
require 'mkmf'

# true expected, returns false
have_func('rb_p')
```

## Configuration Details

* Output of `rbx -v`:
`rubinius 3.27 (2.2.2 628fe1c2 2016-04-15 3.4.2) [x86_64-linux-gnu]` : installed from ruby-build & rbenv
* Output of `uname -a`:
`Linux localhost.localdomain 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Distribution name (in case of Linux/BSD): CentOS 7

**Comment by brixen** [comment]
@jkr2255 we don't build a library, so there's nothing for mkmf to link against to check for the existence of symbols like that. Since all mkmf does is define a macro like HAVE_ABC, we just do that directly when C-exts need it. If you take a look at `machine/include/capi/ruby/defines.h`, you should be able to add what you need. If you could send a PR, I can merge and tag a release.
