### ISSUE TITLE
Segfault while running the tests for the mysql2 gem

### ISSUE THREAD

**Issue by thedrow** [rubinius/rubinius#3662]
## Problem

I run the test suite for mysql2 and got a segfault.
## How to Reproduce

Please keep this as simple as possible and provide either a set of steps or a
script/application to reproduce this problem (and remove this sentence).
## Configuration Details
- Output of `rbx -v`: rubinius 3.36 (2.2.2 f23df637 2016-06-05 3.6.2) [x86_64-darwin13.4.0]
- Output of `uname -a`: Darwin OmerK.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
- Distribution name (in case of Linux/BSD): OSX
## Stack Trace

https://gist.github.com/thedrow/64e4739383b8bcf23bc7ff714a27c8b8

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
