### ISSUE TITLE
The sudden-death round-up.

### ISSUE THREAD

**Issue by digitalextremist** [rubinius/rubinius#3664]
This is a catch-all ticket to include #3658, but more specifically enumerate root causes of that ticket and other associated issues, per @brixen's research, after `3.36`... tracing through `2.5gb+` core-dump's, etc.

Copied summaries from gitter:
- [ ] Managed finalizer on halt aborting in the global method cache.
- [ ] Fiber messing up switching stacks.
- [ ] A corrupt CallSite/InlineCache.

Some associated debug data:
- https://gist.github.com/brixen/fd860e823d5ab1b6420a6ddae2083087#file-gistfile3-txt
- https://gist.github.com/brixen/fd860e823d5ab1b6420a6ddae2083087#file-gistfile2-txt-L72

**Comment by digitalextremist** [comment]
@brixen verified the `machine.fiber.stack_size` is being set properly, and got another stack trace directly from the log this time:

* https://gist.github.com/digitalextremist/a2bbeeab4beab118ed57c369d7754672

As well as `dumps/core.Y`

**Comment by digitalextremist** [comment]
Radical amounts of progress on this but off `GitHub` for all those waiting with anticipation ( :laughing: )

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
