### ISSUE TITLE
Timeout: One thread per Timeout instance; consolidate.

### ISSUE THREAD

**Issue by digitalextremist** [rubinius/rubinius#3665]
Per recent discovery/realization while debugging: `Timeout` is taking up one thread per instance.
- [ ] Refactor to share one thread across all timeouts.
- [ ] With monotonic counters.

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
