### ISSUE TITLE
Performance - #sprintf causes internal mutex/lock contention on Date#to_s calls

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3667]
## Problem

When calling `to_s` on a Date object we end up calling this code:

```
def to_s() format('%.4d-%02d-%02d', year, mon, mday) end
```

In a multi-threaded program that is calling this method a lot, the threads all end up contending for the lock on the cache entry for that format string.

See backtrace below.
## How to Reproduce

```
require 'date'

date = Date.today

(0..100).to_a.map do
  Thread.new { puts date.to_s }
end.join
```
## Configuration Details
- Output of `rbx -v`:
  `rubinius 3.37.c3 (2.2.2 d49a89ad 2016-06-07 3.8.0) [x86_64-darwin14.5.0]`
- Output of `uname -a`: OS X 10.10.5
- Distribution name (in case of Linux/BSD): OS X 10.10
## Stack Trace

https://gist.github.com/chuckremes/23f101b0e78c38865e7e74eeb3bd21be

**Comment by chuckremes** [comment]
Here's a better script.

```
require 'date'

Thread.abort_on_exception = true
threads = []
Iterations = 10_000

threads += (0..100).to_a.map do
  Thread.new do
    date = Date.today
    i = 0

    Iterations.times do
      date += 1
      date.to_s
      i += 1
    end

    raise "oops, was [#{i}] instead of [#{Iterations}]" if i < Iterations

    date
  end
end

p threads.size
threads.each { |thread| p thread.value }
```

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.

Contributions in the form of PRs for any of the areas of focus above are appreciated.
