### ISSUE TITLE
Logger debugging enhancement.

### ISSUE THREAD

**Issue by digitalextremist** [rubinius/rubinius#3669]
As of `3.37` we've had `Fiber` activity in the log, which for `Celluloid` opens an entirely new world of possibilities for debugging. With one thing preventing that ( which was already discussed, on Gitter ):
- [x] The ignored paths in the call site for `Fiber` activity needs to be configurable, because `Celluloid` conceals the true call site, like so...

```
Jun  9 10:59:54 [25765] fiber: new: ruby.11, 10601, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25831] fiber: new: ruby.11, 10605, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25866] fiber: new: ruby.11, 10595, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25810] fiber: new: ruby.11, 10610, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25846] fiber: new: ruby.11, 10609, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25743] fiber: new: ruby.11, 11134, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25807] fiber: new: ruby.11, 10699, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25849] fiber: new: ruby.11, 11133, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25911] fiber: new: ruby.11, 10585, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25721] fiber: new: ruby.11, 10596, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
Jun  9 10:59:54 [25803] fiber: new: ruby.11, 10610, /usr/local/rvm/gems/rubinius-3.37/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:9
```

The ultimate caller needs to be discoverable in order for real debugging to be done on `Fiber` activity, especially to be able to determine the exact cause of `Rubinius` issues, rather than working purely from core dump files or real-time debugging with `gdb`/other.
---

Less important but awesome would be the ability to piece apart logs.
- [ ] Rather than `per-user` only, `per-process` would be great as a non-default option, and with file naming not based on `PID` but on the calling script name, with absolute path. So say, if the script called is `/path1/path2/path3/file1.rb` the log filename would be `rbx-<user>-file1-path1_path2_path3.log`

**Comment by chuckremes** [comment]
@digitalextremist I think the second item is well within your capability. Time for your first (?) patch to rubinius!

I'd recommend adding a `-X` command line switch to turn that behavior on and default to the current behavior.

**Comment by digitalextremist** [comment]
Hadn't thought of that @chuckremes, I think you're right. I will claim the second piece and use that as an entry-point to code contributions.

**Comment by brixen** [comment]
@digitalextremist I'm not following the second piece. Here's some quick info about how configuration variables work: there is a hierarchy that includes: 1. a distinguished file in the user's HOME dir, 2. a distinguished file in the cwd of the process, 3. RBXOPT env var, 4. command line options, and 5. the default values. See https://github.com/rubinius/rubinius/blob/master/machine/environment.cpp#L245-L328

I'll add the first one and would be happy to walk you through the second.

**Comment by digitalextremist** [comment]
@brixen excellent -- I appreciate the help getting up to speed with development, and appreciate the immediate `411` on what I need to know. Very curious and looking forward to this.

**Comment by digitalextremist** [comment]
@brixen I'm not seeing log filters affect the log output. Am I missing a step? I've set `RBXOPT` properly, then run processes: no filtration. When no value is specified, I see `core/*` references also, as if the default itself is not being honored. The only thing I was able to see take effect was passing in an invalid regular expression, which crashes the process at start-time. Am I missing something on my end?

**Comment by digitalextremist** [comment]
Strings I tried:

- `'^.*/celluloid.*$|^core/.*$'`
- `('^.*/celluloid.*$)|(^core/.*$)'`
- `'^core/.*$'`

None has effect. This is what crashed:

- `'^.*\/celluloid.*$|^core\/.*$'`

**Comment by brixen** [comment]
@digitalextremist already mentioned in Gitter, but to close the loop here: a build from source on the box (so not using RVM) shows the filters working. Next step is to try to figure out why they are not working when installed/running under RVM.

**Comment by digitalextremist** [comment]
Updating this with verified results @brixen:

- With the `Ubuntu 14.04` machine we were testing on, using `chruby` and a `3.40` binary in `/opt/rubies/` or `~/.rubies/` alike, the log filtration test case does not filter out `core/filter.rb`

- Same with a fresh install of `Ubuntu 16.04` ... will only show `core/filter.rb` regardless of `RBXOPT` settings, command line arguments, etc.

- *Works when using `ruby-install`* and not just dropping binaries in the right places! I used `ruby-install` on my `Mint 17.2` machine, and the log filtration works properly. But when I download a binary and put it in place then use `chruby` to load it... it behaves like the `Ubuntu` boxes!

**Comment by digitalextremist** [comment]
Verified this is still true under `3.41` binaries as far as I can tell. Will look further into this when possible.

**Comment by brixen** [comment]
@digitalextremist the first enhancement here was implemented and fixed once the C++ regex was properly quoted. Closing the loop on that one.

After giving the 2nd more thought, I'm going to pass on it. I'll explain why: in Rubinius, by the time user code is running, an enormous amount of work has already been performed to set up the process and all the services and components needed to run user code.

The logging facility is one of the very first things started in order to have visibility into the virtual machine as various components are started during the boot process. To support the 2nd feature here, one default log file (or configured log file) would need to be used, and the the logger would need to be restarted with a second one at the point where the user script is invoked.

The processing of command line arguments doesn't happen until the very end of the boot process when the (currently implemented in Ruby) "loader" code is running. To figure out what script may be invoked would require moving command line processing down into the virtual machine instead of in the "userland" loader code.

That sort of coupling isn't something I want to do as one of the key ideas for Rubinius is to make it a language system independent of Ruby. This means allowing whatever language may be implemented determine its own command line processing. The only exception to this are the -X options that are explicitly defined for and processed by the virtual machine.
