### ISSUE TITLE
Can't build EM 1.2.0.1 on OSX w/ macports openssl 1.0.2h on RBX 2.5.8 or 3.39; can on ruby 2.3.1

### ISSUE THREAD

**Issue by saizai** [rubinius/rubinius#3671]
See: https://github.com/eventmachine/eventmachine/issues/722

**Comment by sodabrew** [comment]
I think this is because in https://github.com/rubinius/rubinius/commit/0583b53c5a5fa6da693b1043d88637df3c8c5566 the include flags are added to CFLAGS but not to CXXFLAGS.

The effect is that Rubinius provides CFLAGS that indicate to the EM extconf.rb that it can use an available pre-installed OpenSSL without needed any additional include flags, but the fact that those flags are missing from CXXFLAGS means the actual compile fails.

This edge case occurs because Ruby does not natively provide a CXXFLAGS-based `have_header`, `have_library`, etc. but I'll argue that it's Rubinius at fault for populating one set of flags differently than the other.

**Comment by saizai** [comment]
Not going to dispute you on that, but maybe you could raise it to their
issue tracker and crosslink?

I don't really work with the guts of make/configure, so this is getting out
of my knowledge area.

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.

**Comment by sodabrew** [comment]
Oh actually this was resolved and forgot to get closed by #3794 in e9b88b01ff751ef6dbf5b0a77262957dc1612a58. Thanks again for all your work @brixen!

**Comment by saizai** [comment]
💚
