### ISSUE TITLE
segfault when calling tail recursive function with two paramaters or more

### ISSUE THREAD

**Issue by abnud1** [rubinius/rubinius#3673]
```
def fibacc(n,a,b)
  if n==0
    a
  else
    fibacc n-1,b,a+b
  end
end
def dummyacc(n,a,b,c)
  if(n==0)
    a
  else
    dummyacc n-1,b,c,a+b+c
  end
end
def dummy(n)
  dummyacc n,100,1,1
end
def fib(n)
  fibacc n,0,1
end

puts "hello"
puts dummy(2463)
puts "hi"
puts fib(2510)
```

change 2463 to anything bigger and it will segfault on line `puts dummy(n)`, change 2510 to anything bigger and if it printed dummy(n) then it will segfault on the call to fib.  

if you call `dummyacc` directly then 2464 will be allowed but not bigger !!!

this doesn't happen with one-paramater function

I didn't test more than 3 paramaters but I think `2463` will decrease more and more.
## How to Reproduce
1. 1-define a tail recursive function with two paramaters or more.  
2. 2-call it with number bigger than x(for two paramaters 2510, for three 2463)
## Configuration Details
- Output of `rbx -v`: rubinius 3.40 (2.2.2 4ab64f11 2016-06-12 3.8.0) [x86_64-linux-gnu]
- Output of `uname -a`: Linux abd 4.6.2-1-ARCH #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016 x86_64 GNU/Linux
- Distribution name (in case of Linux/BSD): Arch
## Stack Trace

https://gist.github.com/abnud1/711aff07e640d0d705247ad71cced228

**Comment by brixen** [comment]
@abnud1 thanks for reporting this issue. There are two important parts: 1. Rubinius does not have automatic tailcall recursion elimination; and 2. because of 1, Rubinius can exhaust the stack.

The issue that occurs with 2 is that there is no standard way to handle exhausting the stack. The method Rubinius uses is to calculate a redzone and check that when a method is invoked, the invocation frame size needed won't exceed the space available. Otherwise, the method invocation (or subsequent native function calls) will eventually write into protected memory beyond the stack space and cause a segmentation violation (or segfault).

There was an issue with this with the stack redzone that was fixed recently. If I run your code on 3.64, I get an expected SystemStackError.

Another issue is that the existing interpreter uses way too much stack space per method invocation. This is caused by a huge switch statement and address-of-label array. A new interpreter is partially implemented that will significantly reduce stack usage per method invocation.
