### ISSUE TITLE
RSpec segfaults on it's own specs

### ISSUE THREAD

**Issue by thedrow** [rubinius/rubinius#3689]
## Problem

I tried to run the rspec-core test suite and I got a segfault.
## How to Reproduce

Clone rspec-core from master and run `rake specs`.
## Configuration Details
- Output of `rbx -v`: rubinius 3.51 (2.3.1 b3a77ad4 2016-07-27 3.8.1) [x86_64-darwin15.6.0]
- Output of `uname -a`: Darwin OmerK.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
## Stack Trace

https://gist.github.com/thedrow/0ae645e9490bfb2bbef226d720e1c21a

**Comment by brixen** [comment]
@thedrow I don't get a segfault when I run the specs but I do get a bunch of failures that I'm looking into. Is the segfault reproducible for you or is it sporadic?

**Comment by thedrow** [comment]
It was reproducible on OSX El Capitan.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
