### ISSUE TITLE
NoMethodError when using unparser lib

### ISSUE THREAD

**Issue by lucianolev** [rubinius/rubinius#3694]
## Problem

When loading the unparser library (using require) the script raises an error.
The lib: https://github.com/mbj/unparser

## How to Reproduce
Just exec a script with the line  `require 'unparser'`

Can reproduce on rbx 3.58. 3.14 works as expected.

## Stack Trace

https://gist.github.com/lucianolev/0619401e32b4e19f6ada2d0dc2b04348

**Comment by brixen** [comment]
@lucianolev this is what I've found:

When unparser is loading, it uses IceNine to "deep freeze" a Hash object. IceNine, in turn, recursively traverses an object (ie Hash) via its instance variables, freezing each object as it goes.

By itself, this process is fairly innocuous, aside from the fact that there is no accepted semantic in Ruby that generically says you can arbitrarily freeze an object's state and expect it to continue working.

The problem that leads to the backtrace that you're seeing comes from IceNine code that looks up the class of a "freezer" for a particular object. IceNine caches the classes that it finds here https://github.com/dkubb/ice_nine/blob/2380ec33ef9c3302d0bdf6fb076a5fa6ec9bdc17/lib/ice_nine/freezer.rb#L27-L29 and looks up the class here https://github.com/dkubb/ice_nine/blob/2380ec33ef9c3302d0bdf6fb076a5fa6ec9bdc17/lib/ice_nine/freezer.rb#L67-L72

Since `Hash::Trie` starts with `Hash`, the lookup code calls the Hash freezer and it attempts to call `#default_proc` on an instance of `Hash::Trie`.

So, two things: 1. this is a bug in IceNine; and 2. more importantly, the design of IceNine is deeply problematic.

As I stated above, there is nothing in Ruby that says one should expect to be able to "deep freeze" an arbitrary object. So, it may be possible with a better `#find` method to avoid this specific issue you hit here, but the root of the issues is unchanged.

What Ruby needs is proper support for immutable data structures *where appropriate*. Effort should be put into building these data structures, not recursive "freeze" libraries. Ultimately, `#freeze` and friends should be removed from Ruby, they are a terrible hack.

I'm including all this on the off chance that future readers may be motivated to improve Ruby by implementing or using proper immutable data structures where appropriate and completely avoiding fundamentally broken features like `#freeze`.

**Comment by tmornini** [comment]
@brixen Reading through this, I'm unclear why this works on Ruby, but not on Rubinius. :-)

**Comment by lucianolev** [comment]
@brixen Can you provide more detail on why calling `#default_proc` is wrong? Why is that message implemented in MRI? I would like to understand so I can try a workaround or report the issue to IceNine with a better understanding. 
I understand that IceNine design is flawed as you said and that "freeze/deep freeze" may be bad idea, but I need to use unparser lib as there is not equivalent lib.

Thanks!

**Comment by brixen** [comment]
@tmornini Hash in Ruby is written in C. It has no "Ruby" state that is visible via instance variables. Hash::Trie in Rubinius is a Ruby object that is used to implement the Hash structure. It is visible via instance variables on the Hash object. IceNine treats an instance of Hash::Trie as a Hash via it's "freezer" API, calling a Hash method on it. That doesn't work, anymore than calling a Hash method on some random non-Hash object in your application would work.

@lucianolev please re-read my initial message and the response to @tmornini above. I cannot fix either of those libraries. Once I finish implementing functions, the Hash state won't be visible to Ruby any longer.

**Comment by lucianolev** [comment]
@brixen Thanks, it's now more clear to me :) 
Only one doubt left: What do you mean by "Hash::Trie object is visible via instance variables on the Hash object"? If I send `instance_variables` message to a Hash instance I see no instance variables (btw, an expected behavior, as you told me before).

**Comment by brixen** [comment]
@lucianolev please see below:

```ruby
$ irb
RUBYSDEirb(main):001:0> RUBY_DESCRIPTION
=> "rubinius 3.58 (2.3.1 e3ba6b1a 2016-09-02 3.8.0) [x86_64-darwin13.4.0]"
irb(main):002:0> h = {a:1,b:2}
=> {:a=>1, :b=>2}
irb(main):003:0> h.instance_variables
=> [:@state, :@trie]
irb(main):004:0> h.instance_variable_get :@trie
=> #<Hash::Trie:0x28b0 @bmp=524416 @level=0 @entries=[ #<Hash::Item:0x28b4>, #<Hash::Item:0x28b8> ]>
irb(main):005:0>
```

**Comment by lucianolev** [comment]
@brixen Oh, I was trying with an empty hash (no instance variable is reported in that case).
(Btw, I though you were only going to expose instance variables access for core structures through the Mirror API.)

**Comment by brixen** [comment]
@lucianolev empty Hash has no state, so there are no instance variables. These are purely Ruby objects with Ruby instance variables. Things like Array have C++ fields (at least right now). For the core Ruby classes, *no* state is going to be visible for exactly the reason you see here.

**Comment by lucianolev** [comment]
@brixen I understand. I though Hash was also using C++ fields like Array.
