### ISSUE TITLE
will not run rails executable

### ISSUE THREAD

**Issue by LTheGreats** [rubinius/rubinius#3699]
When I installed rails on Ubuntu 15.10 I got:

rbenv: rails: command not found

The `rails' command exists in these Ruby versions:
  2.3.0
  2.3.1

**Comment by jc00ke** [comment]
We [don't support](https://github.com/rubinius/rubinius/blob/master/CONTRIBUTING.md#version-managers) debugging Ruby version managers. I'm going to close this for now, but please re-open if you cannot  run `rails` with just `Rubinius`, not using `rbenv`.

**Comment by brixen** [comment]
@LTheGreats to elaborate just a bit more, there are three primary "ruby switchers" in use: RVM, rbenv, chruby. We've seen tons of issues related to ruby switchers in the past, and since we don't write them, we cannot easily fix them. Of the three, chruby has been the easiest and most likely to work.

We know that picking a ruby switcher is something important for people because each one seems to have something that the people who choose it really like. That said, both RVM and rbenv make very opinionated decisions about how they work, and those opinions have often disregarded how Rubinius works in the past. On the other hand, chruby just sets a few environment variables and always seems to Just Work™ with Rubinius. So, we advocate using chruby.

If you're interested, I've started this project, [Atom Rubinius terminal](https://github.com/rubinius/atom-rubinius-terminal) to create a pseudo-terminal pane inside the Atom editor. My plan is to have that set up a version of Rubinius that is completely independent of your other system installations of Ruby so that you won't need to mess with RVM, rbenv, chruby, etc. to experiment with Rubinius.

If you use Atom, or would be interested in trying that out, I'll get the binary install working and you'll be able to just open the Atom Rubinius terminal and get started right away.

Let me know if you are interested.
