### ISSUE TITLE
Add regex style PEG flags to rubinius.

### ISSUE THREAD

**Issue by ghost** [rubinius/rubinius#3701]
Add regex style PEG flags to rubinius so we can do PEG parsing in the style of regex.

**Comment by brixen** [comment]
@zacts thanks for putting this on the list.

There are two ways I imagine this could work: 1. customize the Regexp literal parsing so that `/some pattern/p` would interpret the literal source as a PEG instead of a Regexp; and 2. allow a configuration item to interpret all Regexp literals as PEGs instead of Regexps.

Rubinius has a configuration mechanism that can be set at the user level, invocation working directory, env varariable, or command line.

The configuration approach wouldn't require modifying the parser but also wouldn't be as useful to experiment with (and obviously would break code that expects Regexp literals to be Regexps).

**Comment by zacts** [comment]
I just wanted to link this PDF for others who might read this who also might not be familiar with PEG parsing: <http://bford.info/pub/lang/peg.pdf>.

**Comment by brixen** [comment]
This feature may be added in the future. If someone wants to open a PR to add it, that would be appreciated.
