### ISSUE TITLE
Error loading glib2 gem - works under MRI

### ISSUE THREAD

**Issue by harukizaemon** [rubinius/rubinius#3707]
## Problem

```
Could not open library ~/.gem/rbx/2.3.1/gems/glib2-3.0.8/lib/glib2.bundle - dlopen(~/.gem/rbx/2.3.1/gems/glib2-3.0.8/lib/glib2.bundle, 10): Symbol not found: _CONST_ID (LoadError::InvalidExtensionError)
```
## How to Reproduce

```
gem install glib2
ruby -e "require 'glib2'"
```
## Configuration Details
- Installed using ruby-install
- Output of `rbx -v`: rubinius 3.62 (2.3.1 65e96fba 2016-10-14 3.9.0) [x86_64-darwin16.0.0]
- Output of `uname -a`: Darwin AikiBook 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
## Stack Trace

https://gist.github.com/harukizaemon/51ae0d1112093eceac0191faf89e23fb

**Comment by brixen** [comment]
@harukizaemon it's unlikely that Rubinius will ever support any of the gtkX or glib/gnome gems due to code that pokes around inside MRI-specific data structures. You can find various previous issues related to this by searching the Rubinius issue.

Since glib is usually a dependency of another gem, I'm curious which gem you were trying to install that pulls in glib.

**Comment by brixen** [comment]
Rubinius cannot support any C-extensions that depend on accessing the internals of MRI data structures.
