### ISSUE TITLE
provide docs for Rubinius-specific things about the ruby implementation

### ISSUE THREAD

**Issue by abnud1** [rubinius/rubinius#3709]
Now I know that Rubinius is a language platform and it's not specific to ruby so it's reasonable for rubinius book to be language-agnostic .  

But I see Rubinius as actually two things : language platform and a ruby implementation using that platform.  

In my opinion the "Ruby implementation" does deserve some docs.  

Now Ruby itself has docs and so is the standard library but there are some facts that are specific to Rubinius which does deserve its own docs.  

For example in Rubinius the standard library is split into gems, I found this information by googling, I think this kind of information should be found in the docs , in particular I found a hard time looking for "which library comes with Set" and I know others would come too.  

Another example is : I heard that rubinius comes with its own debugger and profiler , those deserve docs as well since almost any debugger/profiler in rubygems (byebug,ruby-prof) is dependent on MRI.  

Last but not least the C-API is not the same as MRI and I was somewhat surprised that I didn't find any info about it on the web.  

Right now without these docs it makes rubinius as a ruby implementation almost unusable for me I'm afraid :( .

**Comment by brixen** [comment]
@abnud1 thanks for bringing up this issue. We do need to document all parts of Rubinius, both Ruby and non-Ruby.

Could you please open [an issue for the Rubinius](https://github.com/rubinius/rubinius-book/issues) with just a simple list of things you need, ideally in order of importance? Feel free to reference this issue for the rationale but you don't need to repeat it there.

I'm going to close this because there is nothing to do in this repository to fix your issue.
