### ISSUE TITLE
RVM cannot install rbx-2 on Ubuntu 12.04 Precise

### ISSUE THREAD

**Issue by BanzaiMan** [rubinius/rubinius#3717]
1. What command did you run?

`rvm install rbx-2 --binary --fuzzy --install` on Ubuntu 12.04

2. What behavior did you expect?

  I expected the installation to complete.

3. What behavior did you get instead?

  I observed the installation fail. https://travis-ci.org/BanzaiMan/travis_production_test/builds/183758512#L139

  This is not an issue on Trusty. https://travis-ci.org/BanzaiMan/travis_production_test/builds/183769405#L109

4. What version of Rubinius?

  N/A

5. What version of operating system?

  Output of `uname -a`:

    $ uname -a
    Linux 44004d6ef886 4.4.27-moby #1 SMP Wed Oct 26 14:21:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  Ubuntu

7. How did you build your version of Rubinius?

  - [x] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by BanzaiMan** [comment]
Looking at the files available from http://binaries.rubini.us, it appears to me that the Precise archives have been removed, and RVM can no longer find a suitable binary archive for use.

**Comment by brixen** [comment]
@BanzaiMan thanks for taking the time to open this issue.

We don't support any version of Rubinius 2.x. We accept issue reports on the current version of Rubinius, which is 3.69 right now. I'll update the [Rubinius install](https://rubinius.com/install/) page and the issues template to more clearly state this.

Even if we were to support Rubinius 2.x, we are not able to build binaries for current versions of Rubinius on Precise because the LLVM packages are too old. We also cannot use the custom LLVM packages because other system libraries are too old. This issue was causing significant confusion for people trying to test with Rubinius on Travis.

Precise end-of-life is April 2017, a few short months away. Other providers, like Heroku, completed migrations from Precise years ago. With our very limited resources we have no extra time to waste supporting OS distros and versions that are easily replaced with readily available modern versions.
