### ISSUE TITLE
Rubinius hangs at exit of test suite with SimpleCov

### ISSUE THREAD

**Issue by eugenk** [rubinius/rubinius#3719]
1. What command did you run?

  I ran `rspec` after including [SimpleCov](https://github.com/colszowka/simplecov) into the project.

2. What behavior did you expect?

  I expected that the command finishes and there is a `coverage` directory with a coverage report.

3. What behavior did you get instead?

  I observed that the call hangs after finishing the tests but before writing the coverage report. The CPU load is at 100% on one core.

4. What version of Rubinius?

  Output of `rbx -v`: rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.9.0) [x86_64-darwin16.3.0]

5. What version of operating system?

  Output of `uname -a`: Darwin dynosaur.fritz.box 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is macOS sierra 10.12.2

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [x] I used ruby-install.  **and chruby**. The command was:
```
   ruby-install rbx -- --llvm-config /usr/local/opt/llvm/bin/llvm-config --with-opt-dir=/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/libyaml:/usr/local/opt/gdbm -L/usr/local/opt/readline/lib -I/usr/local/opt/readline/include
```
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [x] No, I'm not able help debug or I don't have time to help.

I'm glad if I can help debugging it, but I'm not familiar with lldb. I'm just fairly familiar with Ruby in general. I'm trying to migrate a bigger application from MRI to Rubinius because of the parallelity.

---

I created a minimal working example at https://github.com/eugenk/rubinius-simplecov-test. The only interesting file should be the [spec_helper.rb](https://github.com/eugenk/rubinius-simplecov-test/blob/master/spec/spec_helper.rb) (at least the first lines). If the line `SimpleCov.start` is removed, the command `rspec` finishes just fine (except there is no coverage report). Otherwise, `rspec` just hangs actively.

Did I miss something? Is Rubinius not compatible with SimpleCov or the coverage library? Did I do something wrong in this example?

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
