### ISSUE TITLE
Rails 5 server(puma) crashes with stacktrace

### ISSUE THREAD

**Issue by byteg** [rubinius/rubinius#3720]
1. What command did you run?

  I ran `rails s`

2. What behavior did you expect?

  I expected that rails would start successfully.

3. What behavior did you get instead?

  I observed [stacktrace](https://gist.github.com/byteg/fd50433f73866d71ac1168fd0687c7e4)
  Rails server cannot handle any requests.

4. What version of Rubinius?

  Output of `rbx -v`: rubinius 3.69.c4 (2.3.1 07ac9a10 2016-12-14 3.8.0) [x86_64-linux-gnu]

5. What version of operating system?

  Output of `uname -a`: Linux denisk-knote 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Kubuntu 16.10

7. How did you build your version of Rubinius?

  - [ x] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x ] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [ ] Yes, I'm able to help debug, including running commands under lldb.
  - [ x] No, I'm not able help debug or I don't have time to help.

**Comment by hpetru** [comment]
It's not a rubinius issue, this issue is related to `rb-inotify` gem
ref: https://travis-ci.org/guard/rb-inotify/jobs/276840640#L917

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
