### ISSUE TITLE
Rubinius does not compile using rvm

### ISSUE THREAD

**Issue by r-obert** [rubinius/rubinius#3768]
I believe TravisCI is using RVM to install Rubinius. 
I could not install Rubinius locally using RVM.
For CI testing this makes the situation for supporting Rubinius difficult.
I think people will stop testing Rubinius on CI platforms such as Travis (which is quite popular for open source Ruby projects). Then the users of Rubinius will download potentially broken software and have a bad experience while using Rubinius.

Can this situation be fixed (Rubinius is installable through RVM), or Rubinius offers its own solution for use on Travis? Otherwise I imagine Rubinius being dropped by more projects and becoming irrelevant as a real possibility, which would be a shame.

**Comment by r-obert** [comment]
The log:
```
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
ruby-2.4.2@rubinius - #regenerating binstubs - please wait
rbx-3.86 - #downloading rubinius-3.86, this may take a while depending on your connection...
rbx-3.86 - #extracting rubinius-3.86 to /Users/r/.rvm/src/rbx-3.86 - please wait
ruby-2.4.2@rubinius - #bundle install - please wait
rbx-3.86 - #configuring - please wait
rbx-3.86 - #compiling - please wait
Error running '/Users/r/.rvm/wrappers/ruby-2.4.2@rubinius/rake install --trace',
please read /Users/r/.rvm/log/1510275034_rbx-3.86/rake.log
```

Appears related to rubysl-openssl after checking rake.log.

**Comment by brixen** [comment]
@r-obert you ask a very good question, and one that is pretty complicated. I'll try to address it in multiple parts.

Yes, Travis installs Rubinius using RVM, as they do all Ruby engines, as far as I'm aware. There was some work done to use chruby, but I don't think that ever went beyond a beta-ish spike. RVM has been the source of a pretty significant number of issues installing on Travis. Also, RVM installs a _binary_ build of Rubinius (one that we build specifically for RVM to be able to install on Travis).

We've receive over time a huge number of reports about RVM. You can search the issues for them. Unfortunately, we cannot help fix the problems RVM has. I've asked more than one maintainer of RVM to only build Rubinius exactly the way we ask them to build it, and I've been told they won't comply with that. We don't have time to work with them on that.

Other people have had great success using other utilities for installing Ruby. We've had a great experience with chruby, for instance. And a recent post by Akita on Rails [advocates using the asdf manager](http://www.akitaonrails.com/2017/10/24/replacing-rvm-rbenv-nvm-etc-for-asdf) as an alternative.

One of the big goals for the near future is completing the removal of Ruby from the Rubinius build system. This has been a long work in progress, but we've made a lot of improvements and we are close to removing Ruby completely. This is going to make building Rubinius a ton easier for a lot of packaging systems out there, including ones that have struggled to support Rubinius, like Gentoo and Homebrew. I'm really looking forward to that.

Finally, I'm working on being able to provide binary builds for a much bigger set of platforms to make it easier to access Rubinius.

If you have suggestions about how to make it easier for people to access Rubinius, we do appreciate hearing about them. However, we can't support a position like, "I must use RVM, therefore Rubinius must be usable under RVM." There's just not enough of the problem under our control to make that feasible.

**Comment by r-obert** [comment]
Thanks for writing back @brixen.

I have no problem finding another way to install Rubinius locally.
The problem is that Travis does not offer those means, at least not easily and at least not in a way that I would have to figure out myself.

This is a big problem. Rubinius is going to silently loss audience and adoption while this problem remains. That's the point I want to bring to attention. Can we do something about it?

**Comment by brixen** [comment]
@r-obert I'm unsure whether there is anything we can do about it. I've spoken repeatedly to the RVM maintainers. I've spoken to Travis about letting me make it possible for people to chose a different way to install Ruby on Travis. There was an effort to make chruby usable on Travis. I've created this repo so that the problems are visible: https://travis-ci.org/rubinius/travis-canary.

Ultimately, people may choose a different platform than Travis (eg there are Circle CI, CodeShip, the one integrated with GitLab, etc). Or people may disregard Rubinius.

The problem concerns me, but I don't have resources to persuade Travis or RVM to improve the situation, and other than providing more binaries or removing Ruby from the build system so Rubinius is more easy to build, I don't have influence over the situation. I'm considering making [Concourse CI](http://concourse.ci) available, but I don't have the resources to support a lot of free accounts.

**Comment by r-obert** [comment]
Thank you for the information. 
I am open to adding another CI platform available to test Rubinius. 
Do you know which one I should look into?

**Comment by brixen** [comment]
@r-obert I'm not really able to recommend a particular platform. It looks like Circle CI [has an open source friendly option](https://circleci.com/pricing/#faq-section-linux).

Perhaps I'm still not clear on what problem you are running into. Is your Travis build that attempts to use Rubinius failing because Rubinius can't be installed? Or is the problem that you cannot use RVM to install Rubinius locally?

If it is the first problem, could you link to your build? If it's the second one, have you considered just using chruby + ruby-install to use Rubinius locally? Or I could probably build a binary for you that RVM can mount locally.

**Comment by r-obert** [comment]
Very good news :-) 
rbx-3.86 uses a binary on TravisCI, and boots!

The build however fails before it can run a single test:
https://travis-ci.org/pry/pry/jobs/300459512

```
A syntax error has occurred:
    syntax error, unexpected '=': /home/travis/build/pry/pry/spec/hooks_spec.rb:179:13
Code:
        fun = false
            ^
```

Should I open a new issue for that?

**Comment by brixen** [comment]
@r-obert the syntax error is not a bug. :) https://medium.com/@rubinius/rubinius-takes-the-fun-out-of-ruby-21db64ce87a6

**Comment by r-obert** [comment]
Okay. No problem. I'll get a local copy of Rubinius running and see what I can find. Thanks!

**Comment by r-obert** [comment]
It is a little slow to run (over 10 minutes from start to finish - including rvm setup and running the specs themselves), and there are four failures i've tagged to skip on Rubinius (please see build result https://travis-ci.org/pry/pry/jobs/300499821 ) but besides that Rubinius is green. Thank you for the information and help. I will hopefully install Rubinius locally soon. It's been a while.

**Comment by brixen** [comment]
@r-obert thanks for working on this. I'll take a look at the failures.

**Comment by r-obert** [comment]
Thanks @brixen - no problem. Happy to oblige.
