### ISSUE TITLE
Invoking methods with keywords is about 50x slower than without

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3777]
(SEE LAST COMMENT BELOW).

Rbx is about 6x slower invoking methods with keywords than those without keywords. Benched JRuby master (9.1.16?) and MRI 2.5.0 which both show almost no difference in performance between the two.

1. What command did you run?

https://gist.github.com/chuckremes/94fdcb8b7dc5531124c506b210b0bd45

4. What version of Rubinius?

https://gist.github.com/chuckremes/94fdcb8b7dc5531124c506b210b0bd45

5. What version of operating system?

OSX 10.12.6

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [x] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by chuckremes** [comment]
I lied. With keywords is approximately 2x slower. So if you are calling methods 3 deep like in my example, 3 * 2 = 6x. :)

**Comment by chuckremes** [comment]
I lied again. I had a call to `Time.at` in the final method call to simulate some "real work" but of course that ended up swamping the timing of what I really wanted to test.

When I remove it, it shows that keywords actually are about 50x slower than the same method without keywords. Gist to follow...

https://gist.github.com/chuckremes/3d0cc0f6651d3915e89e74133fac56c0

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.

Contributions in the form of PRs for any of the areas of focus above are appreciated.
