### ISSUE TITLE
Cannot install Rake 10.5.0 on Rubinius 3.90

### ISSUE THREAD

**Issue by ms-ati** [rubinius/rubinius#3778]
1. What command did you run?

  I ran `bundle install`

2. What behavior did you expect?

  I expected `rake` to be installed.

3. What behavior did you get instead?

  I observed a `SIGSEGV` as follows: https://travis-ci.org/ms-ati/docile/jobs/328249883

4. What version of Rubinius?

  Output of `rbx -v`:   *3.90*

5. What version of operating system?

  Output of `uname -a`: 
  This is Ubuntu Trusty running within Travis CI, please see the above link

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Ubuntu Trusty running within Travis CI, please see the above link

7. How did you build your version of Rubinius?

  - [x] I used RVM. *as instrumented in Travis CI*
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

*Please note* -- this is my last ditch effort to keep supporting Rubinius in my open source projects via testing on Travis CI. I've made a lot of effort, where most projects have simply removed Rubinius from `.travis.yml`.

**Comment by brixen** [comment]
@ms-ati if you're not using the version of Bundler that's bundled with Rubinius, then you will see segvs because Bundler has unresolved concurrency bugs. RVM is probably updating Bundler for you, despite that I've requested uncountably many times that they do not update Bundler or rubygems versions when building Rubinius.

Please check both your Bundler and rubygems versions. They should be 1.11.2 and 2.6.6 respectively.

An alternative to using RVM is to use chruby and ruby-install. These tools do not suffer from the frequent breakage or other problems of RVM. Also, we cannot fix problems in RVM.

We appreciate your effort to support Rubinius. It's frustrating to us that tools like RVM introduce issues that we make every effort to prevent. Open source is generally built on a lot of good will. We face issues that we didn't create and fix things we didn't break to make the ecosystem better for others. If this has become too burdensome for you, remove Rubinius.

**Comment by ms-ati** [comment]
Hi @brixen thanks for your response! I appreciate your efforts with Rubinius and I really appreciate your taking the time to share the background with me.

👍  to your sentiment:
> Open source is generally built on a lot of good will. We face issues that we didn't create and fix things we didn't break to make the ecosystem better for others.

In that spirit, perhaps we can widen the conversation to see if a solution is possible?

---

@mpapis (author of RVM) and @BanzaiMan (Travis CI maintainer):
  - is it possible to test open source Ruby projects on Rubinius on Travis CI?
  - if so, what am I doing wrong?
  - if not, can we discover from the log of the SIGSEGV in https://travis-ci.org/ms-ati/docile/jobs/328249883 what steps are necessary to make it possible?

Is @brixen 's hypothesis that RVM's installation of Rubinius forces a broken Rubygems and/or Bundler correct?

Or is there something simple I'm doing wrong, that causes SIGSEGV whenever I try to add `rubinius-3` to a `.travis.yml`?

Thanks for any light you might be able to shed on this matter!

**Comment by r-obert** [comment]
> if you're not using the version of Bundler that's bundled with Rubinius, then you will see segvs because Bundler has unresolved concurrency bugs

Surely Rubinius shouldn't segv because of those bugs, though. It's running pure Ruby code after all.

**Comment by brixen** [comment]
@ms-ati thanks for taking more time to deal with this issue. It looks like RVM isn't updating Bundler, if I'm reading your build results correctly. If this is a recent change to RVM, it's really good to see. I should have looked at that more closely to begin with. I've seen so many builds fail because the bundler version was updated. 😢 

We install rake during the binary build process for Rubinius, so I doubt it's anything about installing a particular gem, but more likely just running Bundler. Would it be possible to not use `--jobs=3` during bundle install?

**Comment by brixen** [comment]
@r-obert Bundler is not using pure Ruby code, it uses both Digest and OpenSSL, both of which are MRI C-exts.

**Comment by r-obert** [comment]
Ah okay, I see, thanks for making that clear!

**Comment by brixen** [comment]
@ms-ati quick update, I just released 3.91 and that successfully runs `bundle install && bundle exec rspec` for your repo. Unfortunately, RVM is attempting to install a new version of rubygems, which will not succeed because rubygems is pre-compiled and bundled with Rubinius, so numerous times. Eventually it seems to have given up and reports the gem version as 2.6.6.

The docile build on Rubinius looks successful here: Travis: https://travis-ci.org/rubinius/docile/jobs/329548668.

I'll upgrade rubygems and confirm it works, and if it does, I'll tag 3.92. In the event that RVM tries upgrading Bundler, the build will likely fail. I've got a "concurrent modification of shared memory" check coming in Rubinius that should facilitate finding bugs of that nature. I'll keep you posted.

Please let me know if this resolves your immediate issue.

**Comment by brixen** [comment]
Whoops, hit close by accident. I'll leave it open until you sign off @ms-ati.

**Comment by ms-ati** [comment]
Nice @brixen! So glad that I reached out to you about this :)

**Comment by ms-ati** [comment]
I can verify that I have at least one build that succeeded. I am re-running the latest master build of Docile in Travis here: https://travis-ci.org/ms-ati/docile

If/when the rubinius-3 job passes there, I'll happily mark this as resolved! Thanks again.

**Comment by ms-ati** [comment]
Ok! Now that the Travis outage is over, this definitely fixed it:
https://travis-ci.org/ms-ati/docile

Marking as closed. Thanks again @brixen !

**Comment by brixen** [comment]
@ms-ati thanks for filing the issue. I'll ping you when the Bundler issue is resolved.

**Comment by brixen** [comment]
@ms-ati just FYI, tracking the Bundler concurrency issue here https://github.com/rubinius/rubinius/issues/3781. The 3.93 release includes Bundler 1.16.1, but I'll probably tag 3.94 and roll Bundler back to 1.11.2 unless I can quickly figure this out.

**Comment by brixen** [comment]
@ms-ati ok, one more update, #3781 has a summary of the current state of Bundler running on Rubinius. Unfortunately, we're stuck with 1.11.2 indefinitely. This is just an FYI in case you notice that something is updating the Bundler version on Rubinius.
