### ISSUE TITLE
async-io specs failed with sigsegv somewhere in the guts of openssl

### ISSUE THREAD

**Issue by ioquatix** [rubinius/rubinius#3784]
Here is a backtrace: https://gist.github.com/ioquatix/fc20c0613a55a5aee2ee40c4f26613a6

To reproduce, using rbx-3.99: `git clone git@github.com:socketry/async-io` then `bundle install && rspec`

It only seems to be a problem when including the SSL spec.

I will continue to investigate. I was running on macOS, but I will try Linux next and see if the result is the same.

**Comment by ioquatix** [comment]
In addition, I'm impressed that all the specs are passing for async: https://travis-ci.org/socketry/async/jobs/342182218 - there seems to be a minor issue with code coverage but it's not that important. That means the vast majority of `nio4r` is working correctly.

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
