### ISSUE TITLE
crash under 10.12

### ISSUE THREAD

**Issue by chuckremes2** [rubinius/rubinius#3790]
1. What command did you run?

  I ran the CI run

2. What behavior did you expect?

3. What behavior did you get instead?

  I observed SEGV, see gist at bottom.

4. What version of Rubinius?

3.100.c3

5. What version of operating system?

  Output of `uname -a`:
OSX 10.12.6 specifically

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [x] I built manually from a git clone.
  - [ ] I installed a binary.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

Here's the backtrace for all threads. Thread 2 is the one that crashed. It looks like it's in some new code.

https://gist.github.com/chuckremes2/c20d814d2bc0f553673d0fc0260b851e

**Comment by brixen** [comment]
I'm going to close any issues for platforms other than current macOS or Ubuntu (CI running on Travis) in order to make more progress on completing Rubinius features. Then I want to make a drive to get packages built for all the major distributions and package managers.

If someone wants to take on fixing issues on other platforms in the meantime, that would be appreciated.
