### ISSUE TITLE
Compile from source hangs running tests (at the end)

### ISSUE THREAD

**Issue by voyager131** [rubinius/rubinius#3798]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `sudo ./build.sh --prefix=/usr/local/share/rubinius `

2. What behavior did you expect?

  I expected the software to compile and install

3. What behavior did you get instead?

 It completely compiled and then hung running the tests

4. What version of Rubinius?

3.105

  Output of `rbx -v`: n/a since I can't completely install it.

5. What version of operating system?

  Ubuntu 18.04 LTS (GNU/Linux 4.15.0-22-generic x86_64)

6. What is your operating system distribution, if your operating system has more than one?

n/a

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ x] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [ x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x ] Yes, I'm able to help debug, including running commands under lldb.
  - [x ] No, I'm not able help debug or I don't have time to help.

not familiar with lldb, but pretty good with linux otherwise.
[build-output.txt](https://github.com/rubinius/rubinius/files/2050825/build-output.txt)

**Comment by brixen** [comment]
@voyager131 thanks for opening an issue.

A couple things that may help you with this: 1. once Rubinius is running the specs, it has been completely built, so you can run `rake install` to install it; 2. alternatively, you can run `rake build` then run `bin/mspec ci -V -fs` to run the specs with spec doc output and listing every spec file loaded; 3 even though Rubinius isn't installed, you should be able to invoke it from the build dir with `./bin/rbx`.

Are you by chance running the build as root? That may be the reason for the spec failures. If you are running as root in order to install, you can run `rake spec && sudo rake install`.

**Comment by voyager131** [comment]
I was running the build as root (sudo). I'm out of time today, but will try your suggestion first thing in the morning and post back results here. Thanks for the quick reply.

**Comment by voyager131** [comment]
So I unpacked the source again and ran build as a regular user. It went through as before all the way to the tests and hung about the same place as far as I can tell. The only difference I noticed is that the handful of "F"s that were in the test output instead of "........." were absent. I'm assuming each '.' indicates a passed test and an "F" instead means that test failed.

After waiting for a while to see if the hung test would recover and realizing it didn't, I CTRL+C'd out and ran `./bin/mspec ci -V -fs` as suggested. It goes clean through a bunch of stuff and hangs here:

`/home/depaan/tmp/tmp6/rubinius-3.105/spec/ruby/core/fiber/resume_spec.rb                                                  
Fiber#resume
- can be invoked from the root Fiber
- raises a FiberError if invoked from a different Thread
- returns control to the calling Fiber if called from one
- passes control to the beginning of the block on first invocation
- returns the last value encountered on first invocation
- runs until the end of the block
- runs until Fiber.yield
- resumes from the last call to Fiber.yield on subsequent invocations
- accepts any number of arguments
- sets the block parameters to its arguments on the first invocation
- raises a FiberError if the Fiber is dead
- raises a LocalJumpError if the block includes a return statement
- raises a LocalJumpError if the block includes a break statement
- executes the ensure clause[cursor sits here indefinitely]`

It hangs so bad in fact that I can't CTRL+C out of it. I opened another terminal and ran `ps -aux|grep <user>`, and I notice two defunct rbx processes as well as two /bin/mspec-ci processes. I killed off the defunct processes and all of a sudden the testing resumes.

This makes me think testing is hanging because of a defunct rbx thread. So on that hunch I killed everything including the parent process so that there's nothing in the ps listing that is at all related to rubinius. Then I re-ran `./bin/mspec ci -V -fs`. When it hung again, low and behold, I found a defunct rbx process. I killed it and testing resumed automatically. That happened 2-3 more times, each time killing the defunct rbx process would make the testing resume. But then it hung and nothing defunct I killed made it go again (there were no defunct rbx threads at that point, just some other things I didn't recognize but they wouldn't go away, even with a kill -9) A that point I had to kill the spec-ci process itself to get my prompt back (interestingly enough, when I did that, the defunct processes went away as well... I assume they were children).

So I decided to try again with the build command and see if I could reproduce the behavior with that method. I unpacked the source tarball fresh, and issued the build command as a plain user from inside the source directory. It complied fine as before and hung at the same place during testing. I got it to keep going by watching for and killing defunct rbx processes. But after a point it would no longer continue.

It seems clear there's something wrong with the test suite, at least when it comes to running on my specific system. So after all of that, I ran `rake install` and it worked fine. Let me know if you want any additional information for fixing purposes. It appears I'm good now that rbx is installed.

**Comment by voyager131** [comment]
One question... I had to replace libssl-dev with libssl1.0-dev on my system to properly compile Rubinius. now that it is complied and installed can I put the original libssl-dev back? It's required to install/use rvm.

**Comment by brixen** [comment]
@voyager131 thanks for the detailed account of the spec hangs. I'll find a Vagrant box for 18.04 and try running the specs. The scenario you describe with the defunct process usually happens when the parent doesn't use a `waitpid` syscall to reap a child, but if the child is aborted or segv's, I've seen `waitpid` fail to reap the child.

Why did you need to replace libssl-dev with libssl1.0-dev on your machine? Was there a build failure with OpenSSL or something else? We may need to use some build flags to pick up the right lib without you needing to replace the files.

**Comment by voyager131** [comment]
Indeed, it was openssl-related build failures that caused me to have to replace libssl. That was a hard problem to track down because the error was so ambiguous. I spent nearly two days combing the internet and finally found an obscure post somewhere, which lead me to a hunch which ended up being right. Anyway... you should be able to reproduce the problem with a stock ubuntu 18.04 and download/compile of rubinius. Just for the record. My 18.04 wasn't a clean install. It was an upgrade from 16.04. If you get an update out that "fixes" this issue, let me know and I'll try it out for you on my system. I'm using VM's and have a snapshot I can roll back to that should reproduce the problem or demonstrate that it's fixed.

**Comment by brixen** [comment]
@voyager131 thanks for the additional info. OpenSSL is a major source of problems across systems. :( I'll see what I can figure out with 18.04.

**Comment by voyager131** [comment]
It's up to you as to whether or not you want me to close this issue. As far as I'm concerned, I'm functional, so if the "ticket" represents my problem---case closed. However, if you want to leave it open to track the underlying "bug", that's fine, and I'll be happy to do some more testing for you once we have a "solution". In that case maybe you want to keep it open.

**Comment by brixen** [comment]
@voyager131 thanks again for opening the issue. I'll see if I can add anything to it for others who may run into the same thing after I investigate building on 18.04.

**Comment by mistergibson** [comment]
I experienced this EXACT same issue with version 3.107

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
