### ISSUE TITLE
Rubinius does not install gems binary in $PREFIX/bin and so bundle and pry are not available

### ISSUE THREAD

**Issue by eregon** [rubinius/rubinius#3821]
1. What command did you run?

  I ran `ruby-install rbx 4.5`, added `~/.rubies/rbx-4.5/bin` to my `PATH`,
and then ran `bundle --version`.

Note that I do not have any `GEM_*` variables set, that is I want to use the defaults of RubyGems.

2. What behavior did you expect?

  I expected `Bundler version 1.16.1`, that is I expected `bundle` to be a sibling to `rbx`, and the same for gem-installed executables like `pry`.

3. What behavior did you get instead?

  I observed:
```
$ bundle --version
zsh: command not found: bundle
zsh: exit 127   bundle --version
```

These work, but are both inconvenient workarounds:
```
$ ~/.rubies/rbx-4.5/gems/bin/bundle --version
Bundler version 1.16.1

$ ruby -S bundle --version
Bundler version 1.16.1
```

`bundle --version` (and other gem executables) work after adding `ruby` to `PATH` for other Ruby implementations: I tried MRI, JRuby and TruffleRuby.

This is not limited to `bundle`, gem executables like `pry` also fail with this setup:
```
$ gem install pry
Fetching: method_source-0.9.2.gem (100%)
Successfully installed method_source-0.9.2
Fetching: coderay-1.1.2.gem (100%)
Successfully installed coderay-1.1.2
Fetching: pry-0.12.2.gem (100%)
Successfully installed pry-0.12.2
3 gems installed
$ pry
zsh: command not found: pry
zsh: exit 127   pry
```

Is there a reason to keep that behavior, even though it's incompatible with other Ruby implementations, and makes it more complicated to use Rubinius by requiring a second `PATH` entry (`$PREFIX/gems/bin`) just to use `bundler` or `pry`?

This seems the source of many complications for Ruby managers, which seem necessary only to accommodate Rubinius' choice of a different RubyGems executable directory than `$PREFIX/bin`.

4. What version of Rubinius?

  Output of `rbx -v`: `rubinius 4.5 (2.3.1 f1d4b953 2019-07-13 7.0.1) [x86_64-linux-gnu]`

5. What version of operating system?

  Output of `uname -a`:
`Linux localhost.localdomain 5.0.17-200.fc29.x86_64 #1 SMP Mon May 20 15:39:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

7. How did you build your version of Rubinius?

  - [x] I used ruby-install.

**Comment by brixen** [comment]
@eregon `chruby` works fine with Rubinius, as far as I know, and it's extremely light and interoperates well with other env changers, so that's an option.

What would Rubinius change to accommodate what you're asking for? (I'm not entirely clear). Rubinius very long ago made a number of decisions to avoid conflicting with MRI. If you want to propose a PR, it would probably help evaluate what you're trying to achieve in concrete terms.

**Comment by brixen** [comment]
@eregon the approach I'm going to take for Ruby switchers is to include code in Rubinius that sets them up correctly, instead of relying on the switchers to do it. Not sure when I'll get around to writing that code, though.

Since I intend Rubinius to be installed parallel to MRI without interfering with it, I won't support installing into dirs that would clash with the installed Ruby.

**Comment by eregon** [comment]
Basically this choice means Ruby switchers need code specifically for Rubinius, otherwise it would be as simple as adding `ruby_prefix/bin` to `PATH` and be done.
They already have this code (mentioned in https://github.com/postmodern/chruby/pull/410#issuecomment-515233038), but I find it unfortunate complexity.

Also, it's clearly less convenient (need `rbx -S` all the time) if people want to use Rubinius without a version switcher. Other Rubies would just need adding prefix/bin to `PATH`.

> Since I intend Rubinius to be installed parallel to MRI without interfering with it

I personally think this is a bad idea and very likely to go wrong if e.g., a Rubinius process shells out to say, `rake` or `rspec` as it will then pick MRI instead of Rubinius. But it's your choice, I won't argue more here.

**Comment by brixen** [comment]
@eregon I'm not trying to argue with you about it. It's a simple constraint problem. I understand that you want personal convenience, but

1. You're unwilling to use a Ruby switcher;
2. You're unwilling to add to your PATH;
3. You haven't offered any other solution for not clashing with MRI.

The constraint that I have to solve for is not clashing with MRI. This is a distribution issue for Rubinius because MRI is the incumbent, and I intend for Rubinius to be used far beyond Ruby, too. So I need a solution that meets this constraint.

I've offered to write specific code _inside_ Rubinius just to accommodate the various Ruby switchers to make it as easy as possible to both get Rubinius (considering the vast array of packaging systems out there) and to use Rubinius without conflicting with MRI.

Perhaps defining a shell alias would help your personal case.

**Comment by eregon** [comment]
FWIW, I'm willing to add to PATH, but only `rubinius-prefix/bin`, not anything else. That's what the issue above is about: Rubinius needs two executable directories in PATH when all other Rubies only need one.

Re 3., I think just adding `rubinius-prefix/bin` to PATH should be enough, and one could still have `rbx` as a symlink globally available (as that one is never conflicting).

BTW in Rubinius 4.5, the `erb, gem, irb, rake, rdoc, ri, ruby and testrb` all clash with MRI executables.

**Comment by brixen** [comment]
@eregon ok, thanks for pointing out those clash, I'll try to get that addressed soon.

Am I understanding correctly that as long as all Rubinius executables (including `rbx`) install to a single non-system directory that wouldn't clash with MRI, that would work for your case?

**Comment by eregon** [comment]
> Am I understanding correctly that as long as all Rubinius executables (including `rbx`) install to a single non-system directory that wouldn't clash with MRI, that would work for your case?

I'd want the opposite, a single directory with `rbx`, `gem` and all gem executables, and it should be `prefix/bin` for compatibility with other implementations.
There could be some other directory with just `rbx` that can then be used to avoid clashes if desired.
