### ISSUE TITLE
Rubinius hangs when setting a key of a `Concurrent::Map`

### ISSUE THREAD

**Issue by philr** [rubinius/rubinius#3827]
1. What command did you run?

```sh
$ gem install concurrent-ruby -v 1.1.5
$ rbx -r concurrent -e 'm=Concurrent::Map.new; puts "setting"; m["x"]=1; puts "getting"; puts m["x"]'
```

2. What behavior did you expect?

I expected Rubinius to output the following:

> setting
> getting
> 1

3. What behavior did you get instead?

The "setting" line was output, then Rubinius hangs with 100% CPU utilization. strace reports that the process is waiting on a futex: 

> futex(0x10f45c8, FUTEX_WAIT_PRIVATE, 0, NULL

4. What version of Rubinius?

rubinius 4.7 (10.0 3c35d3f8 2019-12-01 8.0.0) [x86_64-linux-gnu]

The same test works fine with rubinius 3.107 (2.3.1 387c4887 2018-07-15 8.0.0) [x86_64-linux-gnu] (I've not tested earlier 4.x releases).

5. What version of operating system?

Linux ubuntudev 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

My distribution is Ubuntu 19.04.

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [X] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
Hey @philr thanks for opening the issue. Have you been able to debug this at all? Would you be interested in digging into it if I can help get you started?

**Comment by philr** [comment]
Other than running strace to find it was stuck waiting on a futex, I've not done any debugging. I'm happy to run commands to capture some stack traces, process dumps, etc, but I don't really have the time to dig into this right now.

**Comment by brixen** [comment]
@philr thanks again for opening the issue. A bit more explanation of the issue: recently I added the ability to tag `nil` values so that locating where a nil value originated (which is often distant from where a `NoMethodError` may be raised) would be possible. Unfortunately, this requires handling all equality checks for `nil` in a special way. This was one of the checks that was missed.

Another change that I've been slowly making is to replace all "primitive" functions with proper instructions so that the semantics of a program can be fully understood by only looking at how source code is compiled to the instruction set. If this had already been completed, this sort of defect (ie missing a special check for `nil`) wouldn't occur.

One other thing, what you observed in the strace was likely not be "stuck" in a futex, but repeatedly entering a futex because the naive implementation of CAS (compare and swap) simply loops optimistically expecting eventually to achieve the update operation, but that would never happen in the case of a tagged `nil`. If a debugger had been available, it would likely have been very easy for you to identify this looping behavior. I've started work on a new console interface (ie replacement for IRB) that includes a debugging mode to make this easy.
