### ISSUE TITLE
Repository Update/Scan Reminder

### ISSUE THREAD

**Issue by TuanNguyen2807** [rubinius/rubinius#3856]
Your repository has not been updated or scanned in the last 30 days. Please address this issue.

**Comment by jcouball** [comment]
Hey @jc00ke -- Happy New Year!

I noticed issues like this one and  #3855 in my repository as well. I haven't been able to figure out what they are from. I am guessing someone experimenting with DevOps tools or AI?

Examples from my repo:
* https://github.com/ruby-git/ruby-git/issues/779 (4 similar "Repository Update/Scan Reminder" issues were opened)
* https://github.com/ruby-git/ruby-git/issues/766 (15 similar "Suggestion" issues were opened)

I am considering just blocking these users since I never got a response from them.

**Comment by jc00ke** [comment]
Happy new year to you too @jcouball!

I've heard these are going around, generated by LLMs. What a fun time 😜
