### ISSUE TITLE
much slower Nokogiri iteration

### ISSUE THREAD

**Issue by ghazel** [rubinius/rubinius#965]
A simple example of recursively iterating through a Nokogiri::XML document is over 5 times slower with rbx compared to MRI. This was noticed in a real application, and I used the profiler to narrow it down to this. Here's the code:

```ruby
require 'nokogiri'
require 'benchmark'

d = File.open(ARGV[0]){|f| f.read }
s = Nokogiri::XML(d)

def iterfun s
  s.xpath("./*").each do |c|
    iterfun c
  end
end

t = Benchmark.realtime do
  iterfun s
end
puts "done in #{t}"
```

You'll need a big XML file. This code makes one:

```ruby
puts "<root>"
100.times do |j|
  puts "  <foo>#{j}"
  100.times do |i|
    puts "    <bar>#{i}</bar>"
  end
  puts "  </foo>"
end
puts "</root>"
```

**Comment by brixen** [comment]
@ghazel thanks for filing this issue. Apologies for letting it languish so long. There are multiple issues tied up here. Ultimately, Nokogiri is not suited for use with Rubinius because of severe issues with concurrency and the nature of the MRI C-API. As mentioned above, we advocate using Oga.

Regarding performance generally, in the near future we will introduce a number of new instructions to improve performance of String, Array, and Hash operations, as well as some new managed object types. We'll also be doing additional work on the JIT to optimized these instructions. Finally, over the past year, we've added various facilities for better runtime analysis and we'll be working on more of that. Ultimately, the goal is to improve actual program performance with continual feedback versus the often highly misleading synthetic benchmark approach to performance optimization.

Because this issue focuses on Nokogiri, which is a dead-end on Rubinius, I'm going to close it.
